### ISSUE TITLE
[Bug]  java.lang.IllegalArgumentException: Non-positive period.

### ISSUE THREAD

**Issue by ChangjunZhang** [apache/streampark#1030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Kerberos authentication cluster, an exception is thrown when quick start is run. The third parameter of time.schedule in HadoopUtils cannot be 0, and an exception is thrown when the final return of tgtRefreshTime is 0

kerberos 认证集群，当运行quick-start程序时抛出异常，HadoopUtils中time.schedule的第三个参数不能为0，而tgtRefreshTime的最终返回为0时抛出异常

### StreamX Version

1.2.3-release  branch build 

### Java Version

1.8

### Flink Version

1.14.3

### Scala Version of Flink

2.11.12

### Error Exception

```log
2022-05-12 19:33:00 | ERROR | streamx-build-pipeline-executor-0 | com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl:418] java.lang.IllegalArgumentException: Non-positive period.
        at java.util.Timer.schedule(Timer.java:247)
        at com.streamxhub.streamx.common.util.HadoopUtils$$anonfun$hdfs$1.apply(HadoopUtils.scala:230)
        at com.streamxhub.streamx.common.util.HadoopUtils$$anonfun$hdfs$1.apply(HadoopUtils.scala:216)
        at scala.Option.getOrElse(Option.scala:121)
        at com.streamxhub.streamx.common.util.HadoopUtils$.hdfs(HadoopUtils.scala:216)
        at com.streamxhub.streamx.common.util.HdfsUtils$.exists(HdfsUtils.scala:85)
        at com.streamxhub.streamx.common.fs.HdfsOperator$.exists(HdfsOperator.scala:29)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.checkFlinkEnv(EnvInitializer.java:244)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl.checkEnv(ApplicationServiceImpl.java:414)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$FastClassBySpringCGLIB$$4cca1efc.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$EnhancerBySpringCGLIB$$f81517c0.checkEnv(<generated>)
        at com.streamxhub.streamx.console.core.service.impl.ApplBuildPipeServiceImpl$1.onStart(ApplBuildPipeServiceImpl.java:182)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:163)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:162)
        at scala.util.Try$.apply(Try.scala:192)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$class.launch(BuildPipeline.scala:162)
        at com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkYarnApplicationBuildPipeline.launch(FlinkYarnApplicationBuildPipeline.scala:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2022-05-12 19:33:00 | ERROR | streamx-build-pipeline-executor-0 | com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkYarnApplicationBuildPipeline:77] [StreamX] [streamx-packer] building pipeline has failed. | appName=Flink SQL Demo
java.lang.IllegalArgumentException: Non-positive period.
        at java.util.Timer.schedule(Timer.java:247)
        at com.streamxhub.streamx.common.util.HadoopUtils$$anonfun$hdfs$1.apply(HadoopUtils.scala:230)
        at com.streamxhub.streamx.common.util.HadoopUtils$$anonfun$hdfs$1.apply(HadoopUtils.scala:216)
        at scala.Option.getOrElse(Option.scala:121)
        at com.streamxhub.streamx.common.util.HadoopUtils$.hdfs(HadoopUtils.scala:216)
        at com.streamxhub.streamx.common.util.HdfsUtils$.exists(HdfsUtils.scala:85)
        at com.streamxhub.streamx.common.fs.HdfsOperator$.exists(HdfsOperator.scala:29)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.checkFlinkEnv(EnvInitializer.java:244)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl.checkEnv(ApplicationServiceImpl.java:414)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$FastClassBySpringCGLIB$$4cca1efc.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$EnhancerBySpringCGLIB$$f81517c0.checkEnv(<generated>)
        at com.streamxhub.streamx.console.core.service.impl.ApplBuildPipeServiceImpl$1.onStart(ApplBuildPipeServiceImpl.java:182)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:163)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:162)
        at scala.util.Try$.apply(Try.scala:192)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$class.launch(BuildPipeline.scala:162)
        at com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkYarnApplicationBuildPipeline.launch(FlinkYarnApplicationBuildPipeline.scala:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
javax.websocket.EncodeException: No suitable encoder found
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendObjectImpl(WebSocketSessionRemoteEndpoint.java:357)
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendObject(WebSocketSessionRemoteEndpoint.java:340)
        at com.streamxhub.streamx.console.core.websocket.WebSocketEndpoint.pushNotice(WebSocketEndpoint.java:90)
        at com.streamxhub.streamx.console.core.service.impl.MessageServiceImpl.push(MessageServiceImpl.java:53)
        at com.streamxhub.streamx.console.core.service.impl.MessageServiceImpl$$FastClassBySpringCGLIB$$1a2eaf65.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.streamxhub.streamx.console.core.service.impl.MessageServiceImpl$$EnhancerBySpringCGLIB$$81cf8ae4.push(<generated>)
        at com.streamxhub.streamx.console.core.service.impl.ApplBuildPipeServiceImpl$1.onFinish(ApplBuildPipeServiceImpl.java:276)
        at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$class.launch(BuildPipeline.scala:180)
        at com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkYarnApplicationBuildPipeline.launch(FlinkYarnApplicationBuildPipeline.scala:37)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Screenshots

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/22833148/168072021-013e3aa7-f965-4cbe-b243-d95bfca5f8f0.png">
![image](https://user-images.githubusercontent.com/22833148/168072474-bdade095-01c9-4b12-a032-e620a690227b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
can you fix this bug? welcome to submit a PR.

**Comment by zck573693104** [comment]
i can  fix this bug .
let me try it.
