### ISSUE TITLE
[Bug] executionMode: kubernetes-application, savePoint path is null or invalid.

### ISSUE THREAD

**Issue by xinge-1** [apache/streampark#1069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

k8s  application模式下，任务运行过程中无法正确停止。

### StreamX Version

streamx-console-service-1.2.2

### Java Version

java version "1.8.0_181"

### Flink Version

flink:1.13-scala_2.11-java8

### Scala Version of Flink

flink:1.13-scala_2.11-java8

### Error Exception

```log
java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl.lambda$cancel$3(ApplicationServiceImpl.java:961)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.streamxhub.streamx.flink.submit.FlinkSubmitter$$anonfun$stop$1.apply(FlinkSubmitter.scala:61)
	at com.streamxhub.streamx.flink.submit.FlinkSubmitter$$anonfun$stop$1.apply(FlinkSubmitter.scala:56)
	at com.streamxhub.streamx.flink.proxy.FlinkShimsProxy$$anonfun$proxy$1.apply(FlinkShimsProxy.scala:67)
	at com.streamxhub.streamx.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:40)
	at com.streamxhub.streamx.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:67)
	at com.streamxhub.streamx.flink.submit.FlinkSubmitter$.stop(FlinkSubmitter.scala:56)
	at com.streamxhub.streamx.flink.submit.FlinkSubmitter.stop(FlinkSubmitter.scala)
	at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl.lambda$null$2(ApplicationServiceImpl.java:959)
	... 4 more
Caused by: org.apache.flink.util.FlinkException: [StreamX] executionMode: kubernetes-application, savePoint path is null or invalid.
	at com.streamxhub.streamx.flink.submit.trait.FlinkSubmitTrait$class.cancelJob(FlinkSubmitTrait.scala:406)
	at com.streamxhub.streamx.flink.submit.impl.KubernetesNativeApplicationSubmit$.cancelJob(KubernetesNativeApplicationSubmit.scala:38)
	at com.streamxhub.streamx.flink.submit.trait.KubernetesNativeSubmitTrait$class.doStop(KubernetesNativeSubmitTrait.scala:100)
	at com.streamxhub.streamx.flink.submit.impl.KubernetesNativeApplicationSubmit$.doStop(KubernetesNativeApplicationSubmit.scala:91)
	at com.streamxhub.streamx.flink.submit.trait.FlinkSubmitTrait$class.stop(FlinkSubmitTrait.scala:135)
	at com.streamxhub.streamx.flink.submit.impl.KubernetesNativeApplicationSubmit$.stop(KubernetesNativeApplicationSubmit.scala:38)
	at com.streamxhub.streamx.flink.submit.FlinkSubmit$.stop(FlinkSubmit.scala:49)
	at com.streamxhub.streamx.flink.submit.FlinkSubmit.stop(FlinkSubmit.scala)
	... 16 more
```

### Screenshots

![image](https://user-images.githubusercontent.com/76768331/172104581-96f297e3-1928-47fa-9bbd-fd140eb0cc73.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinge-1** [comment]
在flink-conf.yaml配置文件定义savepoint路径后解决。
