### ISSUE TITLE
flink sql  catalog parse error

### ISSUE THREAD

**Issue by lpn666** [apache/streampark#1158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when I use catalog in flink sql , I got an error , At the same time , I use this normaly in flink sql client. 

### StreamX Version

1.2.4

### Java Version

8

### Flink Version

1.14.4

### Scala Version of Flink

2.11

### Error Exception

```log
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: A catalog with name [USE CATALOG myhive] does not exist.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:261) ~[flink-dist_2.11-1.14.4.jar:1.14.4]
	... 12 more
```

### Screenshots

![image](https://user-images.githubusercontent.com/26716574/176847392-1b1a7c5c-1e76-491e-8199-b674c68890bb.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
你有尝试过 myhive.db.tableName 方式调用吗

**Comment by lpn666** [comment]
> 你有尝试过 myhive.db.tableName 方式调用吗

试过，那个可以的。我觉着这应该是个bug，1.2.3版本时候用这个语句直接报错。然后到了1.2.3前端不报错了，后端解析报错了，所以寻思提个bug。

**Comment by wolfboys** [comment]
> > 你有尝试过 myhive.db.tableName 方式调用吗
> 
> 试过，那个可以的。我觉着这应该是个bug，1.2.3版本时候用这个语句直接报错。然后到了1.2.3前端不报错了，后端解析报错了，所以寻思提个bug。

自行编译下最新的1.2.4版本试试

**Comment by ai-smalleryu** [comment]
> > 你有尝试过 myhive.db.tableName 方式调用吗
> 
> 试过，那个可以的。我觉着这应该是个bug，1.2.3版本时候用这个语句直接报错。然后到了1.2.3前端不报错了，后端解析报错了，所以寻思提个bug。

从新下载一下1.2.3的包，我看1.2.3的源码中这个问题没有的

**Comment by lpn666** [comment]
1.2.3确实没有，我编译的最新版本的1.2.4dev是有这个问题的，暂时回退到1.2.3了，等新的发布版吧。
