### ISSUE TITLE
[Bug] Savepoints is not the path of the last checkpoint file.

### ISSUE THREAD

**Issue by COBHzhangfei** [apache/streampark#1253]
### Search before asking

- [x] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Sometimes it is not the path of the last checkpoint file that is saved, but the penultimate one, which results in an error when the checkpoint file cannot be found at startup.

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
Stack trace: ExitCodeException exitCode=2:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:933)
at org.apache.hadoop.util.Shell.run(Shell.java:844)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1123)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:237)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:317)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Container exited with a non-zero exit code 2
Failing this attempt. Failing the application.
```

### Screenshots

![87e8f0b621c55fbae9c86ff7b9e2e78](https://user-images.githubusercontent.com/45984707/179938172-094a556d-1322-492b-bc29-0b31b811150c.png)

![85c07daba787dbb9b622e0f571bf501](https://user-images.githubusercontent.com/45984707/179938092-7db0a8b0-289f-43d0-9dd6-dab8f2e48ac5.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
i will fix this bug
