### ISSUE TITLE
docker-compose building error

### ISSUE THREAD

**Issue by littttttttlePig** [apache/streampark#1417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

#Purpose：build docker images and docker-compose.yml

**When i execute build.sh shell script,and until building webapp by frontend-maven-plugin,it throws an exception.**

**I have tried multiple versions of node and multiple compilation methods, including: `npm run build:mix` and `yarn build:mix`. But neither！But I pull the code to the local to compile the webapp separately, this is feasible**

### Can be seen in the Error Exception

##contains information(such as `npm run build:mix`)：
### maven error:
```text
INFO] --- frontend-maven-plugin:1.12.1:npm (npm install) @ streamx-console-service ---
[INFO] Running 'npm install' in /root/streamx/streamx-console/streamx-console-service/../streamx-console-webapp
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] 
[INFO] audited 1662 packages in 10.713s
[INFO] 
[INFO] 110 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO] 
[INFO] found 20 vulnerabilities (2 low, 8 moderate, 9 high, 1 critical)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:npm (npm run build:mix) @ streamx-console-service ---
[INFO] Running 'npm run build:mix' in /root/streamx/streamx-console/streamx-console-service/../streamx-console-webapp
[INFO] 
[INFO] > streamx-console-webapp@2.0.0 build:mix /root/streamx/streamx-console/streamx-console-webapp
[INFO] > cross-env VUE_APP_ENV=mixin vue-cli-service build
[INFO] 
[INFO]  ERROR  Error loading /root/streamx/streamx-console/streamx-console-webapp/vue.config.js:
[INFO]  ERROR  Error: Cannot find module 'deepmerge'
[INFO] Require stack:
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/src/config/index.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/src/utils/themeUtil.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/vue.config.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-shared-utils/lib/module.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-shared-utils/index.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-service/bin/vue-cli-service.js
[INFO] Error: Cannot find module 'deepmerge'
[INFO] Require stack:
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/src/config/index.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/src/utils/themeUtil.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/vue.config.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-shared-utils/lib/module.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-shared-utils/index.js
[INFO] - /root/streamx/streamx-console/streamx-console-webapp/node_modules/@vue/cli-service/bin/vue-cli-service.js
[INFO]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[INFO]     at require (node:internal/modules/cjs/helpers:102:18)
[INFO]     at Object.<anonymous> (/root/streamx/streamx-console/streamx-console-webapp/src/config/index.js:1:19)
[INFO]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[INFO]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[INFO]     at Module.load (node:internal/modules/cjs/loader:981:32)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! streamx-console-webapp@2.0.0 build:mix: `cross-env VUE_APP_ENV=mixin vue-cli-service build`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the streamx-console-webapp@2.0.0 build:mix script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2022-08-19T14_07_48_824Z-debug.log
```
### npm building error
```text
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/streamx/streamx-console/streamx-console-webapp/node/node',
1 verbose cli   '/root/streamx/streamx-console/streamx-console-webapp/node/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:mix'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v16.14.2
4 verbose run-script [ 'prebuild:mix', 'build:mix', 'postbuild:mix' ]
5 info lifecycle streamx-console-webapp@2.0.0~prebuild:mix: streamx-console-webapp@2.0.0
6 info lifecycle streamx-console-webapp@2.0.0~build:mix: streamx-console-webapp@2.0.0
7 verbose lifecycle streamx-console-webapp@2.0.0~build:mix: unsafe-perm in lifecycle true
8 verbose lifecycle streamx-console-webapp@2.0.0~build:mix: PATH: /root/streamx/streamx-console/streamx-console-webapp/node/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/streamx/streamx-console/streamx-console-webapp/node_modules/.bin:/root/streamx/streamx-console/streamx-console-service/../streamx-console-webapp/node:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin:/usr/local/src/flink/flink-1.13.6/bin:/usr/local/src/danny_test/hadoop-3.2.4/bin:/usr/local/src/danny_test/hadoop-3.2.4/sbin:
9 verbose lifecycle streamx-console-webapp@2.0.0~build:mix: CWD: /root/streamx/streamx-console/streamx-console-webapp
10 silly lifecycle streamx-console-webapp@2.0.0~build:mix: Args: [ '-c', 'cross-env VUE_APP_ENV=mixin vue-cli-service build' ]
11 silly lifecycle streamx-console-webapp@2.0.0~build:mix: Returned: code: 1  signal: null
12 info lifecycle streamx-console-webapp@2.0.0~build:mix: Failed to exec build:mix script
13 verbose stack Error: streamx-console-webapp@2.0.0 build:mix: `cross-env VUE_APP_ENV=mixin vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/streamx/streamx-console/streamx-console-webapp/node/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:526:28)
13 verbose stack     at ChildProcess.<anonymous> (/root/streamx/streamx-console/streamx-console-webapp/node/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:526:28)
13 verbose stack     at maybeClose (node:internal/child_process:1092:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
14 verbose pkgid streamx-console-webapp@2.0.0
15 verbose cwd /root/streamx/streamx-console/streamx-console-webapp
16 verbose Linux 5.15.0-41-generic
17 verbose argv "/root/streamx/streamx-console/streamx-console-webapp/node/node" "/root/streamx/streamx-console/streamx-console-webapp/node/node_modules/npm/bin/npm-cli.js" "run" "build:mix"
18 verbose node v16.14.2
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error streamx-console-webapp@2.0.0 build:mix: `cross-env VUE_APP_ENV=mixin vue-cli-service build`
22 error Exit status 1
23 error Failed at the streamx-console-webapp@2.0.0 build:mix script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
[dsaad.md](https://github.com/streamxhub/streamx/files/9383021/dsaad.md)

### StreamX Version

1.2.3 or 1.2.2

### Java Version

8

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
maven install error
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
It is recommended to use the dev branch

**Comment by littttttttlePig** [comment]
> It is recommended to use the dev branch

I took your advice, but can you tell me how to do it? I want to get a 1.2.2-release

**Comment by MonsterChenzhuo** [comment]
1.dev分支已经做了docker-compse 你可以一键部署，参阅官方文档http://www.streamxhub.com/docs/user-guide/docker-deployment
2.历史版本有很多bug

**Comment by littttttttlePig** [comment]
> 1.dev分支已经做了docker-compse 你可以一键部署，参阅官方文档http://www.streamxhub.com/docs/user-guide/docker-deployment 2.历史版本有很多bug

期待自定义外置MySQL的docker-compose
