### ISSUE TITLE
[Bug] Cannot discover a connector using option: 'connector'='starrocks' 

### ISSUE THREAD

**Issue by JasonChen-ecnu** [apache/streampark#1456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

streamx 的 Development Mode 为 flink sql，部署方式 yarn per-job，将数据写入 starrocks，在页面上传了 flink-connector-starrocks 包，任务报错。尝试不在页面上传 connector 包，直接将包放在 uploads 目录下或 uploads 同级目录 flink lib 目录下，仍然报错。streamx 版本 1.2.3，flink 版本 1.15.1 ，flink-connector-starrocks 版本 1.2.3_flink-1.15。另外尝试写 flink sql代码，直接在flink集群用命令行提交，数据正常写入。

### StreamX Version

1.2.3

### Flink Version

1.15.1

### Scala Version of Flink

2.12

### Error Exception

```log
Caused by: org.apache.flink.table.api.ValidationException: Cannot discover a connector using option: 'connector'='starrocks'
	at org.apache.flink.table.factories.FactoryUtil.enrichNoMatchingConnectorError(FactoryUtil.java:728)
	at org.apache.flink.table.factories.FactoryUtil.discoverTableFactory(FactoryUtil.java:702)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:257)
	... 54 more
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'starrocks' that implements 'org.apache.flink.table.factories.DynamicTableFactory' in the classpath.

Available factory identifiers are:

blackhole
datagen
filesystem
kafka
print
upsert-kafka
	at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:538)
	at org.apache.flink.table.factories.FactoryUtil.enrichNoMatchingConnectorError(FactoryUtil.java:724)
	... 56 more
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
No matter which mode is used to add or modify dependencies (upload | POM), you need to click the go-online button again to publish the tasks, and these dependencies will take effect

**Comment by JasonChen-ecnu** [comment]
@wolfboys 没有go-online按键吧，只有添加依赖的apply，和任务submit之后的 launch application按键，最后start application

**Comment by JasonChen-ecnu** [comment]
我的理解是这样的，如果没有执行 launch application，是无法执行 start application 的，所以无论是添加的jar包还是依赖，都应该添加成功了

**Comment by JasonChen-ecnu** [comment]
可是在执行完 launch application 后，执行 start application，仍然报Cannot discover a connector using option: 'connector'='starrocks'这个错误。

**Comment by alextinng** [comment]
Caused by: org.apache.flink.table.api.ValidationException: Cannot discover a connector using option: 'connector'='jdbc'
	at org.apache.flink.table.factories.FactoryUtil.enrichNoMatchingConnectorError(FactoryUtil.java:587)
	at org.apache.flink.table.factories.FactoryUtil.getDynamicTableFactory(FactoryUtil.java:561)
	at org.apache.flink.table.factories.FactoryUtil.createTableSink(FactoryUtil.java:180)
	... 72 more
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'jdbc' that implements 'org.apache.flink.table.factories.DynamicTableFactory' in the classpath.

Available factory identifiers are:

blackhole
datagen
filesystem
mysql-cdc
print

![image](https://github.com/apache/incubator-streampark/assets/17078980/af62d876-e28d-40f4-96ee-dcb8b15f4e74)
