### ISSUE TITLE
[Bug]运行自定义jar包报错

### ISSUE THREAD

**Issue by wangzhen-wudangshan** [apache/streampark#1561]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

运行自定义jar包报错

### StreamPark Version

streamx-1.2.3

### Java Version

jdk 1.8

### Flink Version

flink-1.13.5

### Scala Version of Flink

2.12

### Error Exception

```log
at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:82)
        at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)
        at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:115)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
```

### Screenshots

![6c5ec34ed9badd2dda7f86ff4be2a52](https://user-images.githubusercontent.com/96755853/189296184-87d6997c-474d-426f-9376-87aec352913e.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangzhen-wudangshan** [comment]
![1662708811773](https://user-images.githubusercontent.com/96755853/189296806-40d52006-e378-4c6f-81d0-8f7d37a2b0da.png)

**Comment by 1996fanrui** [comment]
Hi @wangzhen-wudangshan .

From the stack and code(tag=v1.2.3), I think your exception may be caused by `assert cluster != null;`. 

Did you delete your cluster? And did you start an app to a deleted cluster?

BTW, @wolfboys should we optimize the exception? There are too many assert in the code, and some of these can happen. The `java.lang.AssertionError` is too unspecific. 

We should improve the exception, like this:

```
Preconditions.checkState(cluster != null,
    "The clusterId=%s cannot be find, maybe the clusterId is wrong or " +
        "the cluster has been deleted. Please contact the Admin.",
    application.getFlinkClusterId());
``` 

It should be useful for users. Do you think so? If yes, other asserts can be improved too.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/38427477/190064930-c40c9ae5-4aa6-4a44-95a0-2ae2ea4bc1c1.png">

**Comment by wangzhen-wudangshan** [comment]
I did not delete the cluster. 
![1663148914821](https://user-images.githubusercontent.com/96755853/190121821-f3ed1b69-da33-4dac-a338-a3974faf86cb.png)

What is the cause of the problem?

**Comment by 1996fanrui** [comment]
> I did not delete the cluster. ![1663148914821](https://user-images.githubusercontent.com/96755853/190121821-f3ed1b69-da33-4dac-a338-a3974faf86cb.png)
> 
> What is the cause of the problem?

Other apps can be started, right? If yes, you can re-choose the version for this application and start it again.

Or do you join the StreamPark WeChat group? If yes, you can ask in the group or add me.

**Comment by wangzhen-wudangshan** [comment]
应用都不能启动，没有微信群，只加了公众号。

**Comment by 1996fanrui** [comment]
> 应用都不能启动，没有微信群，只加了公众号。

 @wangzhen-wudangshan 
You can send your WeChat id to my mail, i will add you and invite you to the group. My mail is 1996fanrui@gmail.com

**Comment by wangzhen-wudangshan** [comment]
发你了邮箱了，请查收
