### ISSUE TITLE
[Bug]  Could not find streampark-flink-shims jar package on startup

### ISSUE THREAD

**Issue by helloworld969** [apache/streampark#1618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After pulling the dev branch and compiling and deploying, it prompts that the specified jar package cannot be found at startup.
But I found a similar jar in the lib directory, I don't know where the problem happened, so I came to ask for help, thanks

### StreamPark Version

1.2.4

### Java Version

1.8.0

### Flink Version

1.12.2

### Scala Version of Flink

2.12

### Error Exception

```log
[main] INFO org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.apache.streampark.console.StreamParkConsoleBootstrap.main(StreamParkConsoleBootstrap.java:65)
Caused by: java.lang.IllegalArgumentException: streampark-flink-shims jar not exist
        at org.apache.streampark.common.util.AssertUtils$.checkArgument(AssertUtils.scala:483)
        at org.apache.streampark.common.util.AssertUtils.checkArgument(AssertUtils.scala)
        at org.apache.streampark.console.core.runner.EnvInitializer.storageInitialize(EnvInitializer.java:207)
        at org.apache.streampark.console.core.runner.EnvInitializer.run(EnvInitializer.java:88)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 3 more
[main] INFO org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED paused.
[main] INFO org.springframework.scheduling.quartz.SchedulerFactoryBean - Shutting down Quartz Scheduler
[main] INFO org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
[main] INFO org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED paused.
[main] INFO org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
[main] INFO org.apache.streampark.console.core.task.FlinkTrackingTask - flinkTrackingTask StreamPark Console will be shutdown,persistent application to database.
[main] INFO org.apache.streampark.flink.kubernetes.watcher.FlinkK8sEventWatcher - [StreamPark] [flink-k8s] FlinkK8sEventWatcher closed.
[main] INFO org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher - [StreamPark] [flink-k8s] FlinkJobStatusWatcher closed.
[main] INFO org.apache.streampark.flink.kubernetes.watcher.FlinkMetricWatcher - [StreamPark] [flink-k8s] FlinkMetricWatcher closed.
[main] INFO org.apache.streampark.flink.kubernetes.watcher.FlinkCheckpointWatcher - [StreamPark] [flink-k8s] FlinkCheckpointWatcher closed.
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
[Thread-0] INFO org.apache.streampark.console.StreamParkConsoleBootstrap - application shutdown now, pid: 157612
```

### Screenshots

![image](https://user-images.githubusercontent.com/58214262/190582065-d1bb13d9-aacc-48be-96c5-0ee02405da99.png)
![image](https://user-images.githubusercontent.com/58214262/190582046-7ba4c205-ba82-4553-ad65-b56b6e318967.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by helloworld969** [comment]
![image](https://user-images.githubusercontent.com/58214262/190588345-d5b00553-3d8c-471a-b01b-c0f40c28e0cf.png)


Looking at the code, I found that what I need here is the package in the picture above, which is not available in my lib

**Comment by yinshan612** [comment]
![image](https://user-images.githubusercontent.com/85284614/190588581-f5210d5a-0e8d-42b7-b5df-4c131a2335ec.png)
Manually upload the corresponding version of Flink to the lib directory

**Comment by helloworld969** [comment]
Thank you very much. This problem has been solved, but I want to ask why these packages are not packed together?

**Comment by yinshan612** [comment]
Bug has been reported to the official and is being repaired

**Comment by helloworld969** [comment]
thank
