### ISSUE TITLE
Task status error

### ISSUE THREAD

**Issue by yileii** [apache/streampark#1707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The task fails, but the task status is finished on streamPark

### StreamPark Version

1.2.3

### Java Version

1.8

### Flink Version

1.15.2

### Scala Version of Flink

2.12

### Error Exception

```log
2022-09-28 18:54:22,234 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Map -> Sink: Print to Std. Out (2/2)#0 (2f4175fe1f674b53b0b0acffea443) switched from RUNNING to FAILED with failure cause: java.lang.ArrayIndexOutOfBoundsException: 5
        at org.example.Main.lambda$main$95f17bfa$1(Main.java:24)
        at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:233)
        at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134)
        at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105)
        at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:519)
        at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:804)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:753)
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
        at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
