### ISSUE TITLE
cannot view on page （Apache Flink Dashboard -->task manager -->stdout）,The file STDOUT does not exist on the TaskExecutor

### ISSUE THREAD

**Issue by huangkaiyan10** [apache/streampark#1720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

go to  the page （Apache Flink Dashboard -->task manager -->stdout）,cannot view stdout log result. 

error logs as bellow:
 2022-09-30 01:42:06,724 ERROR org.apache.flink.runtime.rest.handler.taskmanager.TaskManagerStdoutFileHandler [] - Failed to transfer file from TaskExecutor znyw-base-flink-demo-1-taskmanager-1-1.
java.util.concurrent.CompletionException: org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$1(AkkaInvocationHandler.java:251) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.util.concurrent.FutureUtils.doForward(FutureUtils.java:1387) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$null$1(ClassLoadingUtils.java:93) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$guardCompletionWithContextClassLoader$2(ClassLoadingUtils.java:92) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$1.onComplete(AkkaFutureUtils.java:45) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.OnComplete.internal(Future.scala:299) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.OnComplete.internal(Future.scala:297) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:224) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:221) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$DirectExecutionContext.execute(AkkaFutureUtils.java:65) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:621) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:25) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:23) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:532) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_345]
Caused by: org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$requestFileUploadByFilePath$24(TaskExecutor.java:2059) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
2022-09-30 01:42:06,749 ERROR org.apache.flink.runtime.rest.handler.taskmanager.TaskManagerStdoutFileHandler [] - Unhandled exception.
org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$requestFileUploadByFilePath$24(TaskExecutor.java:2059) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]

### StreamPark Version

1.2.3

### Java Version

jdk 8

### Flink Version

1.14.6

### Scala Version of Flink

2.11

### Error Exception

```log
2022-09-30 01:42:06,724 ERROR org.apache.flink.runtime.rest.handler.taskmanager.TaskManagerStdoutFileHandler [] - Failed to transfer file from TaskExecutor znyw-base-flink-demo-1-taskmanager-1-1.
java.util.concurrent.CompletionException: org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.runtime.rpc.akka.AkkaInvocationHandler.lambda$invokeRpc$1(AkkaInvocationHandler.java:251) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.util.concurrent.FutureUtils.doForward(FutureUtils.java:1387) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$null$1(ClassLoadingUtils.java:93) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$guardCompletionWithContextClassLoader$2(ClassLoadingUtils.java:92) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_345]
        at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$1.onComplete(AkkaFutureUtils.java:45) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.OnComplete.internal(Future.scala:299) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.OnComplete.internal(Future.scala:297) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:224) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.japi$CallbackBridge.apply(Future.scala:221) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at org.apache.flink.runtime.concurrent.akka.AkkaFutureUtils$DirectExecutionContext.execute(AkkaFutureUtils.java:65) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:621) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:25) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.pattern.PipeToSupport$PipeableFuture$$anonfun$pipeTo$1.applyOrElse(PipeToSupport.scala:23) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:532) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100) ~[flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_5c7d33b4-d35e-4b5d-8836-24d7e85d83fd.jar:1.14.6]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_345]
Caused by: org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$requestFileUploadByFilePath$24(TaskExecutor.java:2059) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
2022-09-30 01:42:06,749 ERROR org.apache.flink.runtime.rest.handler.taskmanager.TaskManagerStdoutFileHandler [] - Unhandled exception.
org.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$requestFileUploadByFilePath$24(TaskExecutor.java:2059) ~[flink-dist_2.11-1.14.6.jar:1.14.6]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huangkaiyan10** [comment]
flink on kubernetes.  flink  web ui   can not view stdout.

**Comment by tuoluzhe8521** [comment]
i have the same problem

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
