### ISSUE TITLE
flink sql job cannot start ,run status always is  INITIALIZING

### ISSUE THREAD

**Issue by huangkaiyan10** [apache/streampark#1722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

flink sql job cannot start ,run status always is  INITIALIZING. and cannnot view logs at streamx.

### StreamPark Version

1.2.2

### Flink Version

1.14.2-2.11

### Scala Version of Flink

jdk 8

### Error Exception

```log
k8s pod error logs :
2022-09-30 03:43:44,216 WARN  org.apache.flink.runtime.webmonitor.retriever.impl.RpcGatewayRetriever [] - Error while retrieving the leader gateway. Retrying to connect to akka.tcp://flink@znyw-base-flink-demo-5.flink-cluster:6123/user/rpc/resourcemanager_*.
2022-09-30 03:43:44,739 INFO  com.streamxhub.streamx.flink.core.FlinkSqlExecutor           [] - [StreamX] create table:CREATE TABLE datagen (
    f_sequence INT,
    f_random INT,
    f_random_str STRING,
    ts AS localtimestamp,
    WATERMARK FOR ts AS ts
  ) WITH (
    'connector' = 'datagen',
    
    'rows-per-second'='5',
    'fields.f_sequence.kind'='sequence',
    'fields.f_sequence.start'='1',
    'fields.f_sequence.end'='500',
    'fields.f_random.min'='1',
    'fields.f_random.max'='500',
    'fields.f_random_str.length'='10'
  )
2022-09-30 03:43:44,819 WARN  org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap [] - Application failed unexpectedly: 
java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_312]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:279) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$1(ApplicationDispatcherBootstrap.java:216) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        ... 13 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Could not execute CreateTable in path `default_catalog`.`default_database`.`datagen`
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
Caused by: org.apache.flink.table.api.ValidationException: Could not execute CreateTable in path `default_catalog`.`default_database`.`datagen`
        at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:845) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:659) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:881) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:742) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.executeSql(FlinkStreamTableTrait.scala:297) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:168) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:85) ~[?:?]
        at scala.collection.immutable.List.foreach(List.scala:392) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:85) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:94) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:29) ~[?:?]
        at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:49) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:27) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
Caused by: org.apache.flink.table.catalog.exceptions.TableAlreadyExistException: Table (or view) default_database.datagen already exists in Catalog default_catalog.
        at org.apache.flink.table.catalog.GenericInMemoryCatalog.createTable(GenericInMemoryCatalog.java:220) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.lambda$createTable$10(CatalogManager.java:661) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:841) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:659) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:881) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:742) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.executeSql(FlinkStreamTableTrait.scala:297) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:168) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:85) ~[?:?]
        at scala.collection.immutable.List.foreach(List.scala:392) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:85) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:94) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:29) ~[?:?]
        at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:49) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:27) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
2022-09-30 03:43:44,830 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Fatal error occurred in the cluster entrypoint.
org.apache.flink.util.FlinkException: Application failed unexpectedly.
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAndShutdownClusterAsync$0(ApplicationDispatcherBootstrap.java:173) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_312]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:279) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$1(ApplicationDispatcherBootstrap.java:216) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_b95b3084-7d40-455d-bd68-f2a7cc4490ec.jar:1.14.2]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]
Caused by: java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957) ~[?:1.8.0_312]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_312]
        ... 15 more
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        ... 13 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Could not execute CreateTable in path `default_catalog`.`default_database`.`datagen`
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
Caused by: org.apache.flink.table.api.ValidationException: Could not execute CreateTable in path `default_catalog`.`default_database`.`datagen`
        at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:845) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:659) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:881) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:742) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.executeSql(FlinkStreamTableTrait.scala:297) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:168) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:85) ~[?:?]
        at scala.collection.immutable.List.foreach(List.scala:392) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:85) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:94) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:29) ~[?:?]
        at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:49) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:27) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
Caused by: org.apache.flink.table.catalog.exceptions.TableAlreadyExistException: Table (or view) default_database.datagen already exists in Catalog default_catalog.
        at org.apache.flink.table.catalog.GenericInMemoryCatalog.createTable(GenericInMemoryCatalog.java:220) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.lambda$createTable$10(CatalogManager.java:661) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:841) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:659) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:881) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:742) ~[flink-table_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.executeSql(FlinkStreamTableTrait.scala:297) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:168) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$$anonfun$executeSql$2.apply(FlinkSqlExecutor.scala:85) ~[?:?]
        at scala.collection.immutable.List.foreach(List.scala:392) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at com.streamxhub.streamx.flink.core.FlinkSqlExecutor$.executeSql(FlinkSqlExecutor.scala:85) ~[?:?]
        at com.streamxhub.streamx.flink.core.FlinkStreamTableTrait.sql(FlinkStreamTableTrait.scala:94) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.handle(SqlClient.scala:29) ~[?:?]
        at com.streamxhub.streamx.flink.core.scala.FlinkStreamTable$class.main(FlinkStreamTable.scala:49) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient$.main(SqlClient.scala:27) ~[?:?]
        at com.streamxhub.streamx.flink.cli.SqlClient.main(SqlClient.scala) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:253) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        ... 12 more
2022-09-30 03:43:44,837 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Shutting KubernetesApplicationClusterEntrypoint down with application status UNKNOWN. Diagnostics Cluster entrypoint has been closed externally..
2022-09-30 03:43:44,838 INFO  org.apache.flink.runtime.blob.BlobServer                     [] - Stopped BLOB server at 0.0.0.0:6124
2022-09-30 03:43:44,839 INFO  org.apache.flink.runtime.jobmaster.MiniDispatcherRestEndpoint [] - Shutting down rest endpoint.
2022-09-30 03:43:45,518 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator        [] - Shutting down remote daemon.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pandong2011** [comment]
--->    Table (or view) default_database.datagen already exists in Catalog default_catalog.             

The error reported by the log is that the table already exists. If the table is not created before, it may be a code problem

**Comment by pandong2011** [comment]
If it is a platform bug, I hope you can provide more information, including how to reproduce the bug

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
