### ISSUE TITLE
Kube Conf File setting of kubernetes session is invalid

### ISSUE THREAD

**Issue by huangkaiyan10** [apache/streampark#1909]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

at setting page ，i new add a flink cluster of kubernetes session and setting Kube Conf File  value is /etc/kubernetes/admin.conf.  and start cluster but exception.
![03fde7120b04029f95e34bc485cdff9](https://user-images.githubusercontent.com/5146180/197984460-585b8744-4898-4d69-9ca5-31eb38c1aa7e.jpg)

![c29dda25287383215a7d3f10c21f3f7](https://user-images.githubusercontent.com/5146180/197984479-a3634b44-84e0-4044-bebe-b4c682625b54.jpg)

![image](https://user-images.githubusercontent.com/5146180/197984577-db0f1bc8-a49a-4c36-8e5d-47f55b61a6c7.png)

### StreamPark Version

1.2.3

### Java Version

jdk8

### Flink Version

1.14.5-2.12

### Scala Version of Flink

2.12

### Error Exception

```log
Caused by: java.nio.file.NoSuchFileException: /etc/kubernetes/admin.conf 
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at org.apache.flink.util.FileUtils.readAllBytes(FileUtils.java:171)
	at org.apache.flink.util.FileUtils.readFile(FileUtils.java:137)
	at org.apache.flink.util.FileUtils.readFileUtf8(FileUtils.java:142)
	at org.apache.flink.kubernetes.kubeclient.FlinkKubeClientFactory.fromConfiguration(FlinkKubeClientFactory.java:80)
	... 22 more
```

### Screenshots

![c29dda25287383215a7d3f10c21f3f7](https://user-images.githubusercontent.com/5146180/197984861-1985cd8e-b4f3-4b64-bf92-89f78b495c3b.jpg)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huangkaiyan10** [comment]
I solve the problem in this way.
cp -rf /etc/kubernetes/admin.conf /root/.kube/config

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
