### ISSUE TITLE
[Bug] client  directory is empty

### ISSUE THREAD

**Issue by Su1024** [apache/streampark#2042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I terminate the streampark service in the local environment (IDEA), after restarting the streampark console, it prompts that client is not exists or empty directory

### StreamPark Version

2.0.0

### Java Version

1.8
### Flink Version

1.13

### Scala Version of Flink

2.12

### Error Exception

```log
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) [spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.3.jar:2.7.3]
	at org.apache.streampark.console.StreamParkConsoleBootstrap.main(StreamParkConsoleBootstrap.java:65) [classes/:?]
Caused by: java.lang.IllegalArgumentException: /Users/streampark-console-service-2.0.0/client is not exists or empty directory 
	at org.apache.streampark.common.util.AssertUtils$.checkArgument(AssertUtils.scala:483) ~[classes/:?]
	at org.apache.streampark.common.util.AssertUtils.checkArgument(AssertUtils.scala) ~[classes/:?]
	at org.apache.streampark.console.core.runner.EnvInitializer.storageInitialize(EnvInitializer.java:186) ~[classes/:?]
	at org.apache.streampark.console.core.runner.EnvInitializer.run(EnvInitializer.java:89) ~[classes/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-2.7.3.jar:2.7.3]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
local environment  please visit: [doc](https://streampark.apache.org/docs/user-guide/development)
