### ISSUE TITLE
[Bug] Exception in uploading jar package to Linux ECS, unable to upload

### ISSUE THREAD

**Issue by avatarTaier** [apache/streampark#2103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The upload of jar package to the Linux ECS is abnormal and cannot be uploaded. It is tested that : 
 this method is the cause。

### StreamPark Version

2.0.0

### Java Version

1.8

### Flink Version

1.14.6

### Scala Version of Flink

2.12.17

### Error Exception

```log
Caused by: java.io.IOException: UT000128: Remote peer closed connection before all data could be read
	at io.undertow.conduits.FixedLengthStreamSourceConduit.exitRead(FixedLengthStreamSourceConduit.java:364)
	at io.undertow.conduits.FixedLengthStreamSourceConduit.read(FixedLengthStreamSourceConduit.java:264)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.channels.DetachableStreamSourceChannel.read(DetachableStreamSourceChannel.java:209)
	at io.undertow.server.HttpServerExchange$ReadDispatchChannel.read(HttpServerExchange.java:2430)
	at org.xnio.channels.Channels.readBlocking(Channels.java:344)
	at io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:201)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:176)
	at io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:226)
	at io.undertow.servlet.spec.HttpServletRequestImpl.parseFormData(HttpServletRequestImpl.java:857)
	... 86 common frames omitted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please check your network connection is ok and request is timed out?

**Comment by avatarTaier** [comment]
After testing, it is not the reason for this network. Only when you test and upload zip packages on the Linux server, there is no problem. Only when you upload jar packages, there is a problem.
