### ISSUE TITLE
[Bug]In k8s execution mode, the field 'Kubernetes ClusterId' was filled in Chinese content ,then build the job occurs the err.

### ISSUE THREAD

**Issue by green241** [apache/streampark#2113]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

- Question desc :
![image](https://user-images.githubusercontent.com/14801784/204761816-28153562-78ae-4985-9356-b8ac1f2f0a06.png)

- Backend Logs :
Refer the 'Error Exception' module.

- Propose : 
Restrict this entry item from entering Chinese.

### StreamPark Version

dev-2.0.0

### Java Version

1.8.0_181

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
FROM apache/flink:1.14.3-scala_2.12
RUN mkdir -p $FLINK_HOME/usrlib
COPY lib $FLINK_HOME/lib/
COPY streampark-flinkjob_测试中文.jar $FLINK_HOME/usrlib/streampark-flinkjob_测试中文.jar
 | appName=测试中文
2022-11-30 08:17:18 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[4/7] success | appName=测试中文
2022-11-30 08:17:18 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[5/7] running => Pull flink app base docker image | appName=测试中文
2022-11-30 08:17:21 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] already pulled docker image from remote register, imageTag=apache/flink:1.14.3-scala_2.12 | appName=测试中文
2022-11-30 08:17:21 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[5/7] success | appName=测试中文
2022-11-30 08:17:21 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[6/7] running => Build flink app docker image | appName=测试中文
2022-11-30 08:17:22 | INFO  | pool-7-thread-1 | org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher:39] [StreamPark] [FlinkJobStatusWatcher]: Status monitoring process begins - pool-7-thread-1
2022-11-30 08:17:22 | INFO  | pool-7-thread-1 | org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher:39] [StreamPark] [FlinkJobStatusWatcher]: End of status monitoring process - pool-7-thread-1
2022-11-30 08:17:23 | ERROR | docker-java-stream--751561844 | com.github.dockerjava.api.async.ResultCallbackTemplate:52] Error during callback
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
	at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
	at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:143)
	at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:222)
	at org.apache.hc.core5.http.io.entity.InputStreamEntity.writeTo(InputStreamEntity.java:96)
	at org.apache.hc.client5.http.impl.classic.RequestEntityProxy.writeTo(RequestEntityProxy.java:106)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:252)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:141)
	at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:583)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:212)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:105)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:182)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
	... 4 common frames omitted
	Suppressed: java.io.IOException: com.sun.jna.LastErrorException: [32] Broken pipe
		at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
		at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
		at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
		at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
		at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCache(ChunkedOutputStream.java:127)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.finish(ChunkedOutputStream.java:184)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.close(ChunkedOutputStream.java:245)
		at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:253)
		... 29 common frames omitted
	Caused by: com.sun.jna.LastErrorException: [32] Broken pipe
		at com.github.dockerjava.transport.DomainSocket.write(Native Method)
		at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
		... 37 common frames omitted
Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.transport.DomainSocket.write(Native Method)
	at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
	... 38 common frames omitted
2022-11-30 08:17:23 | INFO  | streampark-pipeline-watcher-executor-27 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[6/7] failure => Build flink app docker image | appName=测试中文
2022-11-30 08:17:23 | ERROR | streampark-build-pipeline-executor-5 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:75] [StreamPark] [streampark-packer] building pipeline has failed. | appName=测试中文
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.$anonfun$launch$1(BuildPipeline.scala:162)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.launch(BuildPipeline.scala:157)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.launch$(BuildPipeline.scala:155)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.launch(FlinkK8sApplicationBuildPipeline.scala:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	... 1 common frames omitted
Caused by: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
	at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
	at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
	at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:143)
	at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:222)
	at org.apache.hc.core5.http.io.entity.InputStreamEntity.writeTo(InputStreamEntity.java:96)
	at org.apache.hc.client5.http.impl.classic.RequestEntityProxy.writeTo(RequestEntityProxy.java:106)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:252)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:141)
	at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:583)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:212)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:105)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:182)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
	... 4 common frames omitted
	Suppressed: java.io.IOException: com.sun.jna.LastErrorException: [32] Broken pipe
		at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
		at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
		at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
		at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
		at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCache(ChunkedOutputStream.java:127)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.finish(ChunkedOutputStream.java:184)
		at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.close(ChunkedOutputStream.java:245)
		at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:253)
		... 29 common frames omitted
	Caused by: com.sun.jna.LastErrorException: [32] Broken pipe
		at com.github.dockerjava.transport.DomainSocket.write(Native Method)
		at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
		... 37 common frames omitted
Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer
	at com.github.dockerjava.transport.DomainSocket.write(Native Method)
	at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
	... 38 common frames omitted
2022-11-30 08:17:27 | INFO  | pool-7-thread-1 | org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher:39] [StreamPark] [FlinkJobStatusWatcher]: Status monitoring process begins - pool-7-thread-1
2022-11-30 08:17:27 | INFO  | pool-7-thread-1 | org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatus
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by green241** [comment]
Add desc (2022-12-1) : 
When I filled the 'testI18n' into cluster id , it shown as following :
 Message: Deployment.apps "testI18n" is invalid: metadata.name: Invalid value: "testI18n": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "testI18n": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=testI18n, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "testI18n" is invalid: metadata.name: Invalid value: "testI18n": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

Therefore, this field should be paid more attention.

**Comment by green241** [comment]
Add desc (2022.12.22):
https://github.com/apache/incubator-streampark/pull/2185
