### ISSUE TITLE
[Bug] Project ->Add New->Practical ssh failed to connect to the Repository

### ISSUE THREAD

**Issue by winnlight** [apache/streampark#2135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

SSH failed to connect to the Repository 
Http is OK
![image](https://user-images.githubusercontent.com/72123320/205819213-11a82b67-4da6-439e-b8a3-b5e4a460c2a7.png)
Local ssh can connect
<img width="647" alt="image" src="https://user-images.githubusercontent.com/72123320/205819605-5970b9af-0bac-4d06-8418-743d20c4485e.png">

streampark-console error

### StreamPark Version

Version:2.0.0

### Java Version

jdk1.8

### Flink Version

1.15

### Scala Version of Flink

2.12

### Error Exception

```log
Caused by: org.eclipse.jgit.errors.TransportException: git@xxxx/xxx.git: remote hung up unexpectedly
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:313)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:167)
	... 101 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	... 103 common frames omitted
```

### Screenshots

![image](https://user-images.githubusercontent.com/72123320/205819915-91421053-a76f-4b6a-9da6-b3ebe5d1e3f8.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
+1 I have the same problem
