### ISSUE TITLE
[Bug] savepoint can not stop

### ISSUE THREAD

**Issue by zshelloworld** [apache/streampark#2278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
stop application has some problem。
when i stop an application with savepoint ,application cannot stop，running state is always SAVEPOINT or CANCELLING.    My   version is 2.0 rc3. 
![savepoint](https://user-images.githubusercontent.com/86392288/215928576-84e66bf8-b95e-4480-a083-dc250fa1d6d3.jpg)

### StreamPark Version

2.0.0 rc3

### Java Version

1.8+

### Flink Version

1.13.5

### Scala Version of Flink

2.11

### Error Exception

```log
ERROR | flink-restapi-watching-executor-4 | org.apache.streampark.common.util.YarnUtils:75] [StreamPark] yarnUtils restRequest error, detail:
org.apache.http.conn.HttpHostConnectException: Connect to ***.hostname.com:43417 [***.hostname.com/] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.streampark.common.util.HttpClientUtils$.getHttpResult(HttpClientUtils.scala:171)
        at org.apache.streampark.common.util.HttpClientUtils$.httpGetRequest(HttpClientUtils.scala:74)
        at org.apache.streampark.common.util.YarnUtils$$anonfun$14.apply(YarnUtils.scala:255)
        at org.apache.streampark.common.util.YarnUtils$$anonfun$14.apply(YarnUtils.scala:255)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.streampark.common.util.YarnUtils$.request$1(YarnUtils.scala:255)
        at org.apache.streampark.common.util.YarnUtils$.restRequest(YarnUtils.scala:264)
        at org.apache.streampark.common.util.YarnUtils.restRequest(YarnUtils.scala)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.yarnRestRequest(FlinkRESTAPIWatcher.java:743)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.httpJobsOverview(FlinkRESTAPIWatcher.java:697)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.getFromFlinkRestApi(FlinkRESTAPIWatcher.java:268)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.lambda$doWatch$2(FlinkRESTAPIWatcher.java:209)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 24 common frames omitted
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zshelloworld** [comment]
solved by 2.0.0rc5
