### ISSUE TITLE
com.github.dockerjava.api.async.ResultCallbackTemplate:52] Error during callback[Bug] Bug title

### ISSUE THREAD

**Issue by lx-jialin** [apache/streampark#2362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 11

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

1.15.3

### deploy mode

None

### What happened

发布作业时打镜像失败     ClusterId=my-job

### Error Exception

```log
2023-02-24 16:07:34 | INFO  | streampark-pipeline-watcher-executor-9 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[4/7] success | appName=my-job
2023-02-24 16:07:34 | INFO  | streampark-pipeline-watcher-executor-9 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[5/7] running => Pull flink app base docker image | appName=my-job
2023-02-24 16:07:37 | INFO  | streampark-pipeline-watcher-executor-9 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] already pulled docker image from remote register, imageTag=flink:1.16.1-scala_2.12-java11 | appName=my-job
2023-02-24 16:07:37 | INFO  | streampark-pipeline-watcher-executor-9 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[5/7] success | appName=my-job
2023-02-24 16:07:37 | INFO  | streampark-pipeline-watcher-executor-9 | org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline:39] [StreamPark] [streampark-packer] building pipeline step[6/7] running => Build flink app docker image | appName=my-job
2023-02-24 16:07:44 | ERROR | docker-java-stream-779944065 | com.github.dockerjava.api.async.ResultCallbackTemplate:52] Error during callback
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
        at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
        at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
        at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
        at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
        at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:143)
        at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:222)
        at org.apache.hc.core5.http.io.entity.InputStreamEntity.writeTo(InputStreamEntity.java:96)
        at org.apache.hc.client5.http.impl.classic.RequestEntityProxy.writeTo(RequestEntityProxy.java:106)
        at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:252)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:141)
        at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:583)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:212)
        at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:105)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:182)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
        ... 4 common frames omitted
        Suppressed: java.io.IOException: com.sun.jna.LastErrorException: [32] Broken pipe
                at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:92)
                at com.github.dockerjava.transport.DomainSocket$DomainSocketOutputStream.write(DomainSocket.java:185)
                at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:231)
                at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
                at org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
                at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCache(ChunkedOutputStream.java:127)
                at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.finish(ChunkedOutputStream.java:184)
                at org.apache.hc.core5.http.impl.io.ChunkedOutputStream.close(ChunkedOutputStream.java:245)
                at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:253)
                ... 29 common frames omitted
        Caused by: com.sun.jna.LastErrorException: [32] Broken pipe
                at com.github.dockerjava.transport.DomainSocket.write(Native Method)
                at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
                ... 37 common frames omitted
Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer
        at com.github.dockerjava.transport.DomainSocket.write(Native Method)
        at com.github.dockerjava.transport.DomainSocket.write(DomainSocket.java:90)
        ... 38 common frames omitted
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
check your docker and  connection related configuration:
`Caused by: com.sun.jna.LastErrorException: [104] Connection reset by peer`
