### ISSUE TITLE
[Bug] Flink remote on yarn is lost , the run status changes to failed, and cannot be reconnect to running

### ISSUE THREAD

**Issue by tomoson123** [apache/streampark#2453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

8

### Scala Version

2.12.x

### StreamPark Version

1.2.4

### Flink Version

1.14.4

### deploy mode

yarn-application

### What happened

When running a few days, it will lost the all flink tasks remote on yarn, and the all tasks status change to be failed. But the flink tasks on yarn are running correctly. It can't reconnect to change status to running.

### Error Exception

```log
2023-03-17 00:01:34.036 StreamX [streamx-cluster-executor-2-EventThread] ERROR o.a.f.s.c.o.a.c.ConnectionState:307 - Authentication failed
2023-03-17 00:01:34.110 StreamX [flink-tracking-executor-13] ERROR c.s.s.c.core.task.FlinkTrackingTask:295 - get flink checkPoints error: {}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /proxy/application_1674134898018_0172/jobs/06894618b5186e251092baff034577fa/checkpoints. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.http.conn.HttpHostConnectException: Connect to flink03:18190 [flink03/10.12.8.187] failed: Connection refused (Connection refused)
\u0009at org.apache.http.impl.co"[truncated 12744 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.streamxhub.streamx.console.base.util.JacksonUtils.read(JacksonUtils.java:56)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.yarnRestRequest(FlinkTrackingTask.java:762)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.httpCheckpoints(FlinkTrackingTask.java:747)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.handleCheckPoints(FlinkTrackingTask.java:357)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.getFromFlinkRestApi(FlinkTrackingTask.java:293)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.lambda$tracking$2(FlinkTrackingTask.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-03-17 00:01:34.435 StreamX [flink-tracking-executor-0] ERROR c.s.s.c.core.task.FlinkTrackingTask:295 - get flink checkPoints error: {}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /proxy/application_1674134898018_0159/jobs/6b40e820f3ba540b0afe2236d1666469/checkpoints. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.http.conn.HttpHostConnectException: Connect to flink03:18083 [flink03/10.12.8.187] failed: Connection refused (Connection refused)
\u0009at org.apache.http.impl.co"[truncated 12744 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.streamxhub.streamx.console.base.util.JacksonUtils.read(JacksonUtils.java:56)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.yarnRestRequest(FlinkTrackingTask.java:762)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.httpCheckpoints(FlinkTrackingTask.java:747)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.handleCheckPoints(FlinkTrackingTask.java:357)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.getFromFlinkRestApi(FlinkTrackingTask.java:293)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.lambda$tracking$2(FlinkTrackingTask.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Screenshots

![图片](https://user-images.githubusercontent.com/99782266/225852480-8c0704b7-d5ae-499f-a257-513d7648ed55.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
