### ISSUE TITLE
submitting the job bug

### ISSUE THREAD

**Issue by lee-vivi** [apache/streampark#2455]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.13.6

### deploy mode

remote

### What happened

An error occurred when submitting the job。

### Error Exception

```log
java.util.concurrent.CompletionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor619.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.streampark.flink.client.FlinkClient$.$anonfun$submit$1(FlinkClient.scala:60)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxy$1(FlinkShimsProxy.scala:63)
	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:40)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:63)
	at org.apache.streampark.flink.client.FlinkClient$.submit(FlinkClient.scala:55)
	at org.apache.streampark.flink.client.FlinkClient.submit(FlinkClient.scala)
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl.lambda$start$10(ApplicationServiceImpl.java:1533)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
Caused by: java.lang.AbstractMethodError: com.fasterxml.jackson.databind.Module.version()Lcom/starrocks/shade/com/fasterxml/jackson/core/Version;
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:792)
	at org.json4s.jackson.JsonMethods.org$json4s$jackson$JsonMethods$$_defaultMapper(JsonMethods.scala:12)
	at org.json4s.jackson.JsonMethods.org$json4s$jackson$JsonMethods$$_defaultMapper$(JsonMethods.scala:10)
	at org.json4s.jackson.JsonMethods$.org$json4s$jackson$JsonMethods$$_defaultMapper$lzycompute(JsonMethods.scala:55)
	at org.json4s.jackson.JsonMethods$.org$json4s$jackson$JsonMethods$$_defaultMapper(JsonMethods.scala:55)
	at org.json4s.jackson.JsonMethods.mapper(JsonMethods.scala:17)
	at org.json4s.jackson.JsonMethods.mapper$(JsonMethods.scala:17)
	at org.json4s.jackson.JsonMethods$.mapper(JsonMethods.scala:55)
	at org.json4s.jackson.JsonMethods.parse(JsonMethods.scala:20)
	at org.json4s.jackson.JsonMethods.parse$(JsonMethods.scala:19)
	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:55)
	at org.apache.streampark.flink.client.tool.FlinkSessionSubmitHelper$.$anonfun$submitViaRestApi$1(FlinkSessionSubmitHelper.scala:66)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.client.tool.FlinkSessionSubmitHelper$.submitViaRestApi(FlinkSessionSubmitHelper.scala:66)
	at org.apache.streampark.flink.client.impl.RemoteSubmit$.$anonfun$restApiSubmit$1(RemoteSubmit.scala:97)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.client.impl.RemoteSubmit$.restApiSubmit(RemoteSubmit.scala:91)
	at org.apache.streampark.flink.client.impl.RemoteSubmit$.$anonfun$doSubmit$1(RemoteSubmit.scala:48)
	at org.apache.streampark.flink.client.trait.FlinkSubmitTrait.$anonfun$trySubmit$1(FlinkSubmitTrait.scala:176)
	at scala.util.Try$.apply(Try.scala:209)
	at org.apache.streampark.flink.client.trait.FlinkSubmitTrait.trySubmit(FlinkSubmitTrait.scala:174)
	at org.apache.streampark.flink.client.trait.FlinkSubmitTrait.trySubmit$(FlinkSubmitTrait.scala:168)
	at org.apache.streampark.flink.client.impl.RemoteSubmit$.doSubmit(RemoteSubmit.scala:48)
	at org.apache.streampark.flink.client.trait.FlinkSubmitTrait.submit(FlinkSubmitTrait.scala:116)
	at org.apache.streampark.flink.client.trait.FlinkSubmitTrait.submit$(FlinkSubmitTrait.scala:62)
	at org.apache.streampark.flink.client.impl.RemoteSubmit$.submit(RemoteSubmit.scala:38)
	at org.apache.streampark.flink.client.FlinkClientHandler$.submit(FlinkClientHandler.scala:29)
	at org.apache.streampark.flink.client.FlinkClientHandler.submit(FlinkClientHandler.scala)
	... 14 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
