### ISSUE TITLE
Upload Job Jar[internal server error: null]

### ISSUE THREAD

**Issue by denglhh** [apache/streampark#2501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.13.2

### deploy mode

yarn-application

### What happened

Upload a jar and replace the original jar with an internal server error: null. Then, you cannot replace another jar with a different name

### Error Exception

```log
internal server error: null.
```

### Screenshots

![图片](https://user-images.githubusercontent.com/31583324/227402728-15fc9ab4-8789-45e5-9839-ea5ee85a5ce3.png)
![图片](https://user-images.githubusercontent.com/31583324/227402803-3e369d11-1040-4df6-9725-eacf9bf20594.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by denglhh** [comment]
2023-03-24 09:51:12 | INFO  | XNIO-1 task-7 | org.apache.streampark.console.base.handler.GlobalExceptionHandler:53] Internal server error：
java.lang.NullPointerException: null
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl.getMain(ApplicationServiceImpl.java:1142)
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl$$FastClassBySpringCGLIB$$56060f90.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl$$EnhancerBySpringCGLIB$$89a5c139.getMain(<generated>)
	at org.apache.streampark.console.core.controller.ApplicationController.getMain(ApplicationController.java:327)
	at org.apache.streampark.console.core.controller.ApplicationController$$FastClassBySpringCGLIB$$66b4eb44.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.apache.streampark.console.core.aspect.StreamParkAspect.apiAccess(StreamParkAspect.java:66)
	at sun.reflect.GeneratedMethodAccessor498.invoke(Unknown Source)

**Comment by wolfboys** [comment]
fixed, please upgrade version to 2.1.4
