### ISSUE TITLE
[Bug] When Yarn is low on resources, Yarn accepts the app submitted by streampark and is in an accepted state. After a period of time, streampark prompts for timeout and the app on Yarn has not been killed, resulting in the app running after Yarn has resources. The corresponding job status on streampark is still failed.

### ISSUE THREAD

**Issue by frfsz** [apache/streampark#2574]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14

### deploy mode

yarn-application

### What happened

When Yarn is low on resources, Yarn accepts the app submitted by streampark and is in an accepted state. After a period of time, streampark prompts for timeout and the app on Yarn has not been killed, resulting in the app running after Yarn has resources. The corresponding job status on streampark is still failed.

### Error Exception

```log
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.orApply(CompletableFuture.java:1371)
	at java.util.concurrent.CompletableFuture$OrApply.tryFire(CompletableFuture.java:1350)
	at java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1020)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.streampark.common.util.CompletableFutureUtils$$anon$1.call(CompletableFutureUtils.scala:46)
	at org.apache.streampark.common.util.CompletableFutureUtils$$anon$1.call(CompletableFutureUtils.scala:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
	... 8 more
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Can you rewrite the issue title?
