### ISSUE TITLE
Flink job in k8s application mode can't be stopped by stop button

### ISSUE THREAD

**Issue by hunkw123456** [apache/streampark#2699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

Java 8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.13.2

### deploy mode

kubernetes-application

### What happened

A flink job has been started in k8s application mode. Its "Run Status" keeps RUNNING and data cleansing is ongoing. Then I wanner kill this job by "stop" button, after I clicked it:
(1) The status switched to CANCELLING
(2) Status CANCELLING lasted for 10 minutes then converted to FAILED
(3) But the pod raised by this job is still working, and data cleansing is still ongoing
(4) I checked the logs of level error、warn、info, no exceptions was found but an TimeoutException.

So what can I do for further debugging?

### Error Exception

```log
2023-04-10 06:15:45.238 StreamPark [CompletableFutureDelayScheduler] ERROR o.a.s.c.c.s.i.ApplicationServiceImpl:1265 - stop flink job fail.
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.orApply(CompletableFuture.java:1385)
        at java.util.concurrent.CompletableFuture$OrApply.tryFire(CompletableFuture.java:1364)
        at java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1034)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.apache.streampark.common.util.CompletableFutureUtils$anon$1.call(CompletableFutureUtils.scala:46)
        at org.apache.streampark.common.util.CompletableFutureUtils$anon$1.call(CompletableFutureUtils.scala:45)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.TimeoutException: null
```

### Screenshots

![stop 1](https://user-images.githubusercontent.com/131759638/234233727-2672dd4d-df2e-437c-83dd-1ed71870ae61.png)
![stop 2](https://user-images.githubusercontent.com/131759638/234233748-83f0f391-e4d0-449b-b29b-167688a3de94.png)
![stop  3](https://user-images.githubusercontent.com/131759638/234233756-d0e2e6d1-5901-4e06-b1f7-ee6886366b66.png)
![超时异常](https://user-images.githubusercontent.com/131759638/234233765-67643df2-3c28-4593-8ebf-9da3cd88d5ca.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
