### ISSUE TITLE
There are issues when using statement sets in version 2.10, as errors occur. However, no errors are reported when not using them.

### ISSUE THREAD

**Issue by himper** [apache/streampark#2764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1

### Flink Version

1.15.4

### deploy mode

remote

### What happened

In version 2.10, there are issues when submitting a job using statement sets, as errors occur. However, no errors are reported when not using statement sets.

### Error Exception

```log
--------------------------------------- flink version -----------------------------------


     flinkHome    : /streampark/flink/flink1.15.4


     distJarName  : flink-dist-1.15.4.jar


     flinkVersion : 1.15.4


     majorVersion : 1.15


     scalaVersion : 2.12


     shimsVersion : streampark-flink-shims_flink-1.15


-------------------------------------------------------------------------------------------




2023-05-24 15:53:39 | ERROR | XNIO-1 task-1 | org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl:205] verifySql invocationTargetException: java.lang.reflect.InvocationTargetException


	at sun.reflect.GeneratedMethodAccessor517.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl.lambda$verifySql$0(FlinkSqlServiceImpl.java:199)


	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxyVerifySql$1(FlinkShimsProxy.scala:157)


	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:38)


	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxyVerifySql(FlinkShimsProxy.scala:157)


	at org.apache.streampark.flink.proxy.FlinkShimsProxy.proxyVerifySql(FlinkShimsProxy.scala)


	at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl.verifySql(FlinkSqlServiceImpl.java:192)


	at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl$$FastClassBySpringCGLIB$$d657a89c.invoke(<generated>)


	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)


	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)


	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)


	at org.apache.streampark.console.core.service.impl.FlinkSqlServiceImpl$$EnhancerBySpringCGLIB$$2ead161d.verifySql(<generated>)


	at org.apache.streampark.console.core.controller.FlinkSqlController.verify(FlinkSqlController.java:63)


	at org.apache.streampark.console.core.controller.FlinkSqlController$$FastClassBySpringCGLIB$$e1cd5352.invoke(<generated>)


	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)


	at org.apache.streampark.console.core.aspect.StreamParkAspect.apiAccess(StreamParkAspect.java:85)


	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)


	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)


	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)


	at org.apache.streampark.console.core.controller.FlinkSqlController$$EnhancerBySpringCGLIB$$79225658.verify(<generated>)


	at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)


	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)


	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)


	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)


	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)


	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)


	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)


	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)


	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)


	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)


	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)


	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)


	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)


	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)


	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)


	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)


	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)


	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)


	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)


	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)


	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)


	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)


	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)


	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)


	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)


	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)


	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)


	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)


	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)


	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)


	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)


	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)


	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)


	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)


	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)


	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)


	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)


	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)


	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)


	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)


	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)


	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)


	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)


	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)


	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)


	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)


	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)


	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)


	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)


	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)


	at java.lang.Thread.run(Thread.java:750)


Caused by: java.util.NoSuchElementException: next on empty iterator


	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)


	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)


	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)


	at scala.collection.IterableLike.head(IterableLike.scala:109)


	at scala.collection.IterableLike.head$(IterableLike.scala:108)


	at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:198)


	at scala.collection.IndexedSeqOptimized.head(IndexedSeqOptimized.scala:129)


	at scala.collection.IndexedSeqOptimized.head$(IndexedSeqOptimized.scala:129)


	at scala.collection.mutable.ArrayOps$ofRef.head(ArrayOps.scala:198)


	at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2(FlinkSqlValidator.scala:77)


	at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2$adapted(FlinkSqlValidator.scala:76)


	at scala.collection.immutable.List.foreach(List.scala:392)


	at org.apache.streampark.flink.core.FlinkSqlValidator$.verifySql(FlinkSqlValidator.scala:76)


	at org.apache.streampark.flink.core.FlinkSqlValidator.verifySql(FlinkSqlValidator.scala)


	... 136 more




2023-05-24 15:53:39 | INFO  | XNIO-1 task-1 | org.apache.streampark.console.base.handler.GlobalExceptionHandler:54] Internal server error：


java.lang.NullPointerException: null


	at org.apache.streampark.console.core.controller.FlinkSqlController.verify(FlinkSqlController.java:64)


	at org.apache.streampark.console.core.controller.FlinkSqlController$$FastClassBySpringCGLIB$$e1cd5352.invoke(<generated>)


	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)


	at org.apache.streampark.console.core.aspect.StreamParkAspect.apiAccess(StreamParkAspect.java:85)


	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)


	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)


	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)


	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)


	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)


	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)


	at org.apache.streampark.console.core.controller.FlinkSqlController$$EnhancerBySpringCGLIB$$79225658.verify(<generated>)


	at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)


	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)


	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)


	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)


	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)


	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)


	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)


	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)


	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)


	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)


	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)


	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)


	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)


	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/134488881/15fd8d16-2ac2-485b-b7b1-dd517459d696)
![image](https://github.com/apache/incubator-streampark/assets/134488881/b8cbcaea-0664-45e8-9e9c-f33e25a16a60)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by charonjiang** [comment]
我也遇到到了类似的问题，不过我的报错信息是：Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "org.apache.streampark.flink.core.FlinkSqlValidator$.logInfo(Lscala/Function0;)V" the class loader (instance of org/apache/streampark/flink/proxy/ChildFirstClassLoader) of the current class, org/apache/streampark/flink/core/FlinkSqlValidator$, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/apache/streampark/common/util/Logger have different Class objects for the type scala/Function0 used in the signature
        at org.apache.streampark.flink.core.FlinkSqlValidator.verifySql(FlinkSqlValidator.scala) ，看看有没有大佬能解答一下？

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
