### ISSUE TITLE
Please check if your network connection is normal! The network is abnormal

### ISSUE THREAD

**Issue by justsleepping** [apache/streampark#2769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14.6

### deploy mode

yarn-application

### What happened

On the Edit page of flink SQL, click Submit to report an error

Please check if your network connection is normal! The network is abnormal

### Error Exception

```log
2023-05-26 17:20:13.635 StreamPark [flink-restapi-watching-executor-19] ERROR o.a.s.c.c.task.FlinkRESTAPIWatcher:532 - FlinkRESTAPIWatcher getFromYarnRestApi,job was killed and stopFrom NotFound,savePoint expired!
2023-05-26 17:42:14.971 StreamPark [flink-restapi-watching-executor-0] ERROR o.a.streampark.common.util.YarnUtils:75 - [StreamPark] yarnUtils restRequest error, detail:
org.apache.http.NoHttpResponseException: bdp03:42894 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.streampark.common.util.HttpClientUtils$.getHttpResult(HttpClientUtils.scala:171)
        at org.apache.streampark.common.util.HttpClientUtils$.httpGetRequest(HttpClientUtils.scala:74)
        at org.apache.streampark.common.util.YarnUtils$.$anonfun$restRequest$2(YarnUtils.scala:255)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.streampark.common.util.YarnUtils$.request$1(YarnUtils.scala:255)
        at org.apache.streampark.common.util.YarnUtils$.restRequest(YarnUtils.scala:264)
        at org.apache.streampark.common.util.YarnUtils.restRequest(YarnUtils.scala)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.yarnRestRequest(FlinkRESTAPIWatcher.java:749)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.httpJobsOverview(FlinkRESTAPIWatcher.java:703)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.getFromFlinkRestApi(FlinkRESTAPIWatcher.java:270)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.lambda$doWatch$2(FlinkRESTAPIWatcher.java:211)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2023-05-26 17:42:15.928 StreamPark [flink-restapi-watching-executor-34] ERROR o.a.streampark.common.util.YarnUtils:75 - [StreamPark] yarnUtils restRequest error, detail:
org.apache.http.conn.HttpHostConnectException: Connect to bdp03:42894 [bdp03/10.10.203.217] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.streampark.common.util.HttpClientUtils$.getHttpResult(HttpClientUtils.scala:171)
        at org.apache.streampark.common.util.HttpClientUtils$.httpGetRequest(HttpClientUtils.scala:74)
        at org.apache.streampark.common.util.YarnUtils$.$anonfun$restRequest$2(YarnUtils.scala:255)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.streampark.common.util.YarnUtils$.request$1(YarnUtils.scala:255)
        at org.apache.streampark.common.util.YarnUtils$.restRequest(YarnUtils.scala:264)
        at org.apache.streampark.common.util.YarnUtils.restRequest(YarnUtils.scala)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.yarnRestRequest(FlinkRESTAPIWatcher.java:749)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.httpJobsOverview(FlinkRESTAPIWatcher.java:703)
        at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.getFromFlinkRestApi(FlinkRESTAPIWatcher.java:270)
 at org.apache.streampark.console.core.task.FlinkRESTAPIWatcher.lambda$doWatch$2(FlinkRESTAPIWatcher.java:211)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:606)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 23 common frames omitted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by justsleepping** [comment]
When I clear my browser's cookies and then click sumbit, the submission is successful

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
