### ISSUE TITLE
[Bug]start job failed after upgrade from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by guwangwunian** [apache/streampark#2802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_202

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

1.14.6

### deploy mode

yarn-application

### What happened

after upgrade streampark backend from 2.0.0 to 2.1.0, each time when i start the job, i got a error message that shows "argument type mismatch".
then I tried to upgrade  streampark maven dependencies to 2.1.0 in my own java code, no use.
I also tried to reinstall streampark-2.1.0, but still got the same error.

100% happens, is this a streampark bug or just my env problem? 

### Error Exception

```log
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.streampark.flink.client.FlinkClient$.$anonfun$proxy$1(FlinkClient.scala:80)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxy$1(FlinkShimsProxy.scala:60)
	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:38)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:60)
	at org.apache.streampark.flink.client.FlinkClient$.proxy(FlinkClient.scala:75)
	at org.apache.streampark.flink.client.FlinkClient$.submit(FlinkClient.scala:49)
	at org.apache.streampark.flink.client.FlinkClient.submit(FlinkClient.scala)
	at org.apache.streampark.console.core.service.impl.ApplicationServiceImpl.lambda$start$10(ApplicationServiceImpl.java:1544)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/107533918/cc7e69a5-72bd-4b34-80be-61692a119451)
![image](https://github.com/apache/incubator-streampark/assets/107533918/0db2328c-a14f-473c-ac9b-1653bba39433)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please do not run streampark in the your IDE. You can download an dist package from the official website, and then execute startup.sh to start it.
