### ISSUE TITLE
[Bug] Exceeding the tag limit of the cloud provider due to the length of the application name can result in a failed push during the task deployment process

### ISSUE THREAD

**Issue by Fu012345** [apache/streampark#2825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 8

### Scala Version

2.11.x

### StreamPark Version

2.1.0

### Flink Version

1.14

### deploy mode

None

### What happened

Exceeding the tag limit of the cloud provider due to the length of the application name can result in a failed push during the task deployment process（application Name的长度超过云厂商的tag限制会导致任务发布过程中push失败）

### Error Exception

```log
16:32:18.640 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[4/7] success | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:18.646 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[5/7] running => Pull flink app base docker image | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:21.348 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] already pulled docker image from remote register, imageTag=flink:1.14.3-scala_2.12-java8 | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:21.349 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[5/7] success | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:21.356 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[6/7] running => Build flink app docker image | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:25.309 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] built docker image, imageId=75cf870c834b, imageTag=registry.cn-shenzhen.aliyuncs.com/smart_test/streamparkflinkjob-my-namespace-kafka2doris-dws-dws-gaswaterheater-waterpump | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:25.310 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[6/7] success | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:25.317 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[7/7] running => Push flink app docker image | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:25.840 [streampark-pipeline-watcher-executor-0] INFO org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline step[7/7] failure => Push flink app docker image | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
16:32:25.849 [streampark-build-pipeline-executor-1] ERROR org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline - [StreamPark] [streampark-packer] building pipeline has failed. | appName=kafka2doris-dws-dws-gaswaterheater-waterpump
java.util.concurrent.ExecutionException: com.github.dockerjava.api.exception.DockerClientException: Could not push image: denied: requested access to the resource is denied
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.$anonfun$launch$1(BuildPipeline.scala:136)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.launch(BuildPipeline.scala:129)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.launch$(BuildPipeline.scala:127)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.launch(FlinkK8sApplicationBuildPipeline.scala:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not push image: denied: requested access to the resource is denied
	at com.github.dockerjava.core.command.PushImageResultCallback.throwFirstError(PushImageResultCallback.java:42)
	at com.github.dockerjava.api.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:93)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.$anonfun$buildProcess$28(FlinkK8sApplicationBuildPipeline.scala:200)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.$anonfun$buildProcess$28$adapted(FlinkK8sApplicationBuildPipeline.scala:188)
	at org.apache.streampark.flink.packer.docker.package$.usingDockerClient(package.scala:46)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.$anonfun$buildProcess$27(FlinkK8sApplicationBuildPipeline.scala:202)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.$anonfun$execStep$1(BuildPipeline.scala:102)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.execStep(BuildPipeline.scala:97)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline.execStep$(BuildPipeline.scala:96)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.execStep(FlinkK8sApplicationBuildPipeline.scala:42)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.buildProcess(FlinkK8sApplicationBuildPipeline.scala:202)
	at org.apache.streampark.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.buildProcess(FlinkK8sApplicationBuildPipeline.scala:42)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline$$anon$1.call(BuildPipeline.scala:134)
	at org.apache.streampark.flink.packer.pipeline.BuildPipeline$$anon$1.call(BuildPipeline.scala:133)
	... 4 common frames omitted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
