### ISSUE TITLE
[Bug] Fix address err & typos in the code

### ISSUE THREAD

**Issue by onlyotdn** [apache/streampark#2838]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.2.0-SNAPSHOT

### Flink Version

none

### deploy mode

None

### What happened

local start application (and other typos err)

### Error Exception

```log
2023-07-07 14:07:34 | ERROR | main | org.springframework.boot.SpringApplication:821] Application run failed
java.lang.ExceptionInInitializerError: [StreamPark] System initialization check failed, The system initialization check failed. If started local for development and debugging, please ensure the -Dapp.home parameter is clearly specified, more detail: https://streampark.apache.org/docs/user-guide/development
	at org.apache.streampark.console.core.runner.EnvInitializer.run(EnvInitializer.java:86)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.apache.streampark.console.StreamParkConsoleBootstrap.main(StreamParkConsoleBootstrap.java:50)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by onlyotdn** [comment]
@zhoulii PTAL, thanks.
