### ISSUE TITLE
[Bug] k8s 下 Application 模式 的启动报错

### ISSUE THREAD

**Issue by yjz-enter** [apache/streampark#3051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

flink-1.17.1

### deploy mode

kubernetes-application

### What happened

1.streampark 部署在K8s环境，启动的flink job 是flink on k8s Application  模式

2. 排查了权限问题
kubectl get serviceaccount streampark -n default

kubectl create clusterrolebinding flink-role-binding-default --clusterrole=cluster-admin --serviceaccount=default:streampark --namespace=default

### Error Exception

```log
ERROR org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - Fatal error occurred in ResourceManager.
org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start the ResourceManager akka.tcp://flink@yjztest-pg-cdc001.default:6123/user/rpc/resourcemanager_1
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:257) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.rpc.RpcEndpoint.internalCallOnStart(RpcEndpoint.java:198) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.lambda$start$0(AkkaRpcActor.java:622) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.start(AkkaRpcActor.java:621) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleControlMessage(AkkaRpcActor.java:190) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Cannot initialize resource provider.
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:202) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:281) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:252) ~[flink-dist-1.17.1.jar:1.17.1]
	... 25 more
Caused by: java.util.concurrent.ExecutionException: org.apache.flink.util.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient.watchPodsAndDoCallback(Fabric8FlinkKubeClient.java:245) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.KubernetesResourceManagerDriver.watchTaskManagerPods(KubernetesResourceManagerDriver.java:409) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.KubernetesResourceManagerDriver.initializeInternal(KubernetesResourceManagerDriver.java:114) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:92) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:196) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:281) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:252) ~[flink-dist-1.17.1.jar:1.17.1]
	... 25 more
Caused by: org.apache.flink.util.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
	at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperation$1(FutureUtils.java:192) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.concurrent.CompletionException: org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/pods?labelSelector=app%3Dyjztest-pg-cdc001%2Ccomponent%3Dtaskmanager%2Ctype%3Dflink-native-kubernetes&allowWatchBookmarks=true&watch=true. Message: Forbidden.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/pods?labelSelector=app%3Dyjztest-pg-cdc001%2Ccomponent%3Dtaskmanager%2Ctype%3Dflink-native-kubernetes&allowWatchBookmarks=true&watch=true. Message: Forbidden.
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:684) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:664) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.lambda$run$2(WatchConnectionManager.java:126) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	Suppressed: java.lang.Throwable: waiting here
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:169) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:180) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:547) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:83) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient.lambda$null$3(Fabric8FlinkKubeClient.java:236) ~[flink-dist-1.17.1.jar:1.17.1]
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
		at java.lang.Thread.run(Unknown Source) ~[?:?]
2023-09-13 09:09:31,717 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Fatal error occurred in the cluster entrypoint.
org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Could not start the ResourceManager akka.tcp://flink@yjztest-pg-cdc001.default:6123/user/rpc/resourcemanager_1
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:257) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.rpc.RpcEndpoint.internalCallOnStart(RpcEndpoint.java:198) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.lambda$start$0(AkkaRpcActor.java:622) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor$StoppedState.start(AkkaRpcActor.java:621) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleControlMessage(AkkaRpcActor.java:190) ~[flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_cf2e7833-75c2-47e8-b0fe-265ec039ca3e.jar:1.17.1]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.apache.flink.runtime.resourcemanager.exceptions.ResourceManagerException: Cannot initialize resource provider.
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:202) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:281) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:252) ~[flink-dist-1.17.1.jar:1.17.1]
	... 25 more
Caused by: java.util.concurrent.ExecutionException: org.apache.flink.util.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient.watchPodsAndDoCallback(Fabric8FlinkKubeClient.java:245) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.KubernetesResourceManagerDriver.watchTaskManagerPods(KubernetesResourceManagerDriver.java:409) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.KubernetesResourceManagerDriver.initializeInternal(KubernetesResourceManagerDriver.java:114) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.active.AbstractResourceManagerDriver.initialize(AbstractResourceManagerDriver.java:92) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager.initialize(ActiveResourceManager.java:196) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.startResourceManagerServices(ResourceManager.java:281) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.runtime.resourcemanager.ResourceManager.onStart(ResourceManager.java:252) ~[flink-dist-1.17.1.jar:1.17.1]
	... 25 more
Caused by: org.apache.flink.util.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
	at org.apache.flink.util.concurrent.FutureUtils.lambda$retryOperation$1(FutureUtils.java:192) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.concurrent.CompletionException: org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/pods?labelSelector=app%3Dyjztest-pg-cdc001%2Ccomponent%3Dtaskmanager%2Ctype%3Dflink-native-kubernetes&allowWatchBookmarks=true&watch=true. Message: Forbidden.
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/default/pods?labelSelector=app%3Dyjztest-pg-cdc001%2Ccomponent%3Dtaskmanager%2Ctype%3Dflink-native-kubernetes&allowWatchBookmarks=true&watch=true. Message: Forbidden.
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:684) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:664) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.lambda$run$2(WatchConnectionManager.java:126) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[flink-dist-1.17.1.jar:1.17.1]
	at org.apache.flink.kubernetes.shaded.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[flink-dist-1.17.1.jar:1.17.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	Suppressed: java.lang.Throwable: waiting here
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:169) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:180) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:547) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.shaded.io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:83) ~[flink-dist-1.17.1.jar:1.17.1]
		at org.apache.flink.kubernetes.kubeclient.Fabric8FlinkKubeClient.lambda$null$3(Fabric8FlinkKubeClient.java:236) ~[flink-dist-1.17.1.jar:1.17.1]
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
		at java.lang.Thread.run(Unknown Source) ~[?:?]
2023-09-13 09:09:31,790 INFO  org.apache.flink.runtime.blob.BlobServer                     [] - Stopped BLOB server at 0.0.0.0:6124
2023-09-13 09:09:31,790 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Shutting KubernetesApplicationClusterEntrypoint down with application status UNKNOWN. Diagnostics Cluster entrypoint has been closed externally..
```

### Screenshots

![Snipaste_2023-09-13_18-08-59](https://github.com/apache/incubator-streampark/assets/51939654/d3f224b0-a8a5-4c89-9223-bb361a73c57b)
![Snipaste_2023-09-13_18-09-47](https://github.com/apache/incubator-streampark/assets/51939654/553b9a23-d3aa-4b8c-888e-15d64ade4e78)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed in new version
