### ISSUE TITLE
在构建application时，提示权限不对，在本地已经试验过可以用docker pull拉取自定义的flink镜像的，不知道是哪里出了问题？我的镜像仓库是sealer默认的镜像库，本地手工执行docker pull flink1.17.1没问题。该镜像库没有设置auth，所以没有用户名和口令。

### ISSUE THREAD

**Issue by fi-ecavc** [apache/streampark#3167]
在构建application时，提示权限不对，在本地已经试验过可以用docker pull拉取自定义的flink镜像的，不知道是哪里出了问题？我的镜像仓库是sealer默认的镜像库，本地手工执行docker pull flink1.17.1没问题。该镜像库没有设置auth，所以没有用户名和口令。
![Uploading 41e7e6e1260e6ac2b1ed349b463c755.png…]()
![994620f68f9aa30a66ed3da7b7e02af](https://github.com/apache/incubator-streampark/assets/10372053/d8a93a8d-07ad-4d8e-9233-9e71b2d75dae)

_Originally posted by @fi-ecavc in https://github.com/apache/incubator-streampark/discussions/3165_

**Comment by fi-ecavc** [comment]
2023-09-24 13:48:38.240 StreamPark [docker-java-stream-1217387663] ERROR c.g.d.a.async.ResultCallbackTemplate:52 - Error during callback
java.lang.RuntimeException: java.io.IOException: com.sun.jna.LastErrorException: [13] Permission denied
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: com.sun.jna.LastErrorException: [13] Permission denied
        at com.github.dockerjava.transport.DomainSocket.<init>(DomainSocket.java:63)
        at com.github.dockerjava.transport.LinuxDomainSocket.<init>(LinuxDomainSocket.java:41)
        at com.github.dockerjava.transport.DomainSocket.get(DomainSocket.java:140)
        at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:190)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)

**Comment by fi-ecavc** [comment]
sudo 启动streampark解决问题。
