### ISSUE TITLE
k8s NodePort Connection refused

### ISSUE THREAD

**Issue by xiongmozhou** [apache/streampark#3349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.13.6

### deploy mode

kubernetes-application

### What happened

I deployed using the nodePort port, and the task was running normally. However, when I clicked cancel, the task did not respond, the pod was still running, and the connection was rejected. Port 30990 is the nodePort port I exposed

### Error Exception

```log
Caused by: org.apache.flink.shaded.netty4.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.192.0.1:30990
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.flink.shaded.netty4.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEve
```

### Screenshots

1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Thank you for your feedback. I'm very sorry for taking so long to reply to you. I'll take a look at the issue and see if I can answer your question.

**Comment by caicancai** [comment]
It looks like the connection failed. Let me try to see if it can surface.

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
