### ISSUE TITLE
[Bug] Bug title streampark  

### ISSUE THREAD

**Issue by wsczm** [apache/streampark#3411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.13

### deploy mode

yarn-perjob

### What happened

when i run flink cdc task , sreampark down

### Error Exception

```log
java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
        at org.xnio.nio.WorkerThread.execute(WorkerThread.java:620)
        at io.undertow.websockets.jsr.UndertowSession.close0(UndertowSession.java:362)
        at io.undertow.websockets.jsr.UndertowSession.closeInternal(UndertowSession.java:242)
        at io.undertow.websockets.jsr.UndertowSession$3$1.run(UndertowSession.java:402)
        at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:411)
        at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:389)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1085)
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:998)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70)
        at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:204)
        at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:193)
        at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:198)
        at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:387)
        at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186)
        at org.xnio.IoUtils.safeClose(IoUtils.java:152)
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57)
        at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:108)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:507)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wsczm** [comment]
![Uploading 11.png…]()
