### ISSUE TITLE
[Bug] Path resolution exception when submitting tasks in remote mode on Windows environment

### ISSUE THREAD

**Issue by linweijiang** [apache/streampark#3534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2（The dev branch has not yet addressed that）

### Flink Version

1.18.1

### deploy mode

remote

### What happened

In services running locally on Windows using Idea, there is a path conversion exception when submitting tasks in remote mode.

Do we have a dedicated module or a utility class specifically for converting things for Windows? I've done a quick and dirty conversion and it works fine, but I feel it's not elegant enough. There are likely many more areas that require adaptation for the Windows environment.

### Error Exception

```log
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\opt\streampark_workspace\workspace\100003\streampark-flinkjob_test-remote-yarn-local.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.flink.client.program.PackagedProgramUtils.resolveURI(PackagedProgramUtils.java:243)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.submit(FlinkClientTrait.scala:83)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.submit$(FlinkClientTrait.scala:60)
	at org.apache.streampark.flink.client.impl.RemoteClient$.submit(RemoteClient.scala:34)
	at org.apache.streampark.flink.client.FlinkClientHandler$.submit(FlinkClientHandler.scala:40)
	at org.apache.streampark.flink.client.FlinkClientHandler.submit(FlinkClientHandler.scala)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenshaojin** [comment]
I think this is related to the issue of flink. https://wiki.avatr.com/pages/viewpage.action?pageId=21660370

**Comment by chenshaojin** [comment]
I just tested it, and the problem you mentioned does exist. Currently, submitting jobs on Windows does not meet this condition.

**Comment by FrommyMind** [comment]
> I think this is related to the issue of flink. https://wiki.avatr.com/pages/viewpage.action?pageId=21660370

Cannot vist the site. got 403 error


dev-2.1.5 still has this issue

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
