### ISSUE TITLE
flinksql检查报错，无法提交flinksql    Caused by: java.lang.NoSuchFieldError: HIVE

### ISSUE THREAD

**Issue by lisonglin-code** [apache/streampark#3538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk 11.04

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

flink1.18.1

### deploy mode

remote

### What happened

无法提交flinksql,sql检查程序报错

### Error Exception

```log
17:01:19.302 StreamPark [XNIO-1 task-6] ERROR o.a.s.c.c.s.impl.FlinkSqlServiceImpl:205 - verifySql invocationTargetException: java.lang.reflect.InvocationTargetException
......
Caused by: java.lang.NoSuchFieldError: HIVE
        at org.apache.streampark.flink.core.FlinkSqlValidator$.getConfig$1(FlinkSqlValidator.scala:56)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.sqlParserConfigMap$lzycompute(FlinkSqlValidator.scala:69)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.sqlParserConfigMap(FlinkSqlValidator.scala:46)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$4(FlinkSqlValidator.scala:98)
        at scala.util.Try$.apply(Try.scala:213)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2(FlinkSqlValidator.scala:90)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.$anonfun$verifySql$2$adapted(FlinkSqlValidator.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.apache.streampark.flink.core.FlinkSqlValidator$.verifySql(FlinkSqlValidator.scala:76)
        at org.apache.streampark.flink.core.FlinkSqlValidator.verifySql(FlinkSqlValidator.scala)
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/159207500/b236b4fa-723b-4166-a4b9-97b91b4021b0)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Good catch

**Comment by wolfboys** [comment]
hi:

Thanks for your feedback. I have tested and verified locally that the Flink version is 1.18.1, and I did not encounter the issue you reported. Could you provide more details? How did you deploy StreamPark ? Did you start it in the usual way by running scripts, or did you start it for debugging in a local IDE environment? 

<img width="973" alt="image" src="https://github.com/apache/incubator-streampark/assets/13284744/4949446a-b556-4b5b-81f0-0ea8665df5fa">

**Comment by caicancai** [comment]
If there are no other questions, I will close. If you have other questions, you are welcome to reopen.
