### ISSUE TITLE
[Bug] Bug title JDK 17 在mac 系统 build dev-2.1.3 和 release-2.1,2 失败，提示/packages cannot be represented as URI

### ISSUE THREAD

**Issue by wangyeqiang** [apache/streampark#3567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

17.0.10

### Scala Version

2.12.x

### StreamPark Version

2.1.3 和 2.1.2

### Flink Version

1.18

### deploy mode

None

### What happened

报错   java.lang.RuntimeException: /packages cannot be represented as URI

### Error Exception

```log
[INFO] Reactor Summary:
[INFO] 
[INFO] StreamPark Project Parent POM 2.1.3 ................ SUCCESS [ 18.163 s]
[INFO] StreamPark : Shaded Parent 1.0.0 ................... SUCCESS [  0.259 s]
[INFO] StreamPark : Shaded Slf4j 1.0.0 .................... SUCCESS [  1.582 s]
[INFO] StreamPark : Shaded Jackson 1.0.0 .................. SUCCESS [  1.474 s]
[INFO] StreamPark : Common 2.1.3 .......................... SUCCESS [ 42.544 s]
[INFO] StreamPark : Flink Parent 2.1.3 .................... SUCCESS [  0.481 s]
[INFO] StreamPark : Flink Shims Parent 2.1.3 .............. SUCCESS [  0.461 s]
[INFO] StreamPark : Flink Shims Base 2.1.3 ................ FAILURE [  7.914 s]
[INFO] StreamPark : Flink Shims 1.14 2.1.3 ................ SKIPPED
[INFO] StreamPark : Flink Core 2.1.3 ...................... SKIPPED
[INFO] StreamPark : Flink Shims Test 2.1.3 ................ SKIPPED
[INFO] StreamPark : Flink Shims 1.12 2.1.3 ................ SKIPPED


Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
Caused by: java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:175)
	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:213)
	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:64)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:64)
	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:78)
	at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:77)
	at scala.tools.nsc.Global$$anon$4.findMacroClassLoader(Global.scala:477)
	at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:68)
	at scala.reflect.internal.SymbolTable$perRunCaches$$anon$2.apply(SymbolTable.scala:477)
	at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:70)
	at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:70)
	at scala.tools.nsc.Global$$anon$4.defaultMacroClassloader(Global.scala:477)
	at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:88)
	at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:50)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:50)
	at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:43)
	at scala.tools.nsc.Global$$anon$4.standardMacroRuntime(Global.scala:477)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:455)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:452)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:452)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:452)
	at scala.tools.nsc.Global$$anon$4.pluginsMacroRuntime(Global.scala:477)
	at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:37)
	at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:37)
	at scala.tools.nsc.Global$$anon$4.macroRuntime(Global.scala:477)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:631)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:227)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:625)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:612)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:787)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:785)
	at scala.tools.nsc.Global$$anon$4.standardMacroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:439)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.Global$$anon$4.pluginsMacroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:776)
	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:769)
	at scala.tools.nsc.Global$$anon$4.macroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1183)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1243)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1216)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5740)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:5942)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2069)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5644)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2030)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1896)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5647)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5356)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5649)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:103)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1580)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:179)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:177)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:463)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:418)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:405)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:171)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:181)
	at scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:364)
	at scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:122)
	at scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:89)
	at scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:310)
	at scala_maven.ScalaCompileMojo.execute(ScalaCompileMojo.java:108)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	... 7 more
Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
	... 148 more
```

### Screenshots

<img width="752" alt="image" src="https://github.com/apache/incubator-streampark/assets/41089935/6f19dc05-8d1f-406c-b912-89c8c7809027">
<img width="1008" alt="image" src="https://github.com/apache/incubator-streampark/assets/41089935/2ff7f9a2-71de-442f-8c6a-536a7360af1d">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangyeqiang** [comment]
dev版本可以用jdk 17 build成功， dev-2.1.3和release-2.1.2使用jdk11. bulild成功。

**Comment by caicancai** [comment]
dev2.1.3 currently does not support jdk17, please use jdk11 or jdk8 to build
