### ISSUE TITLE
[Bug] streampark yarn session mode is started, the server cannot use the flink command, such as flink list

### ISSUE THREAD

**Issue by cc77944056** [apache/streampark#3837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1.4

### Flink Version

1.19.1

### deploy mode

yarn-session

### What happened

 I started a yarn session service with the normal flink command yarn-session.sh -d on the master node, and the master node can display the job list in the flink list;
  However, a yarn session service is also started on streampark (installed on the master node), and the flink list of the master node or other slave nodes all report an error
  Error display:

### Error Exception

```log
# bin/flink list
Waiting for response...

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.util.FlinkException: Failed to retrieve job list.
        at org.apache.flink.client.cli.CliFrontend.listJobs(CliFrontend.java:453)
        at org.apache.flink.client.cli.CliFrontend.lambda$list$0(CliFrontend.java:434)
        at org.apache.flink.client.cli.CliFrontend.runClusterAction(CliFrontend.java:1216)
        at org.apache.flink.client.cli.CliFrontend.list(CliFrontend.java:430)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1276)
        at org.apache.flink.client.cli.CliFrontend.lambda$mainInternal$10(CliFrontend.java:1367)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.mainInternal(CliFrontend.java:1367)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1335)
Caused by: java.util.concurrent.TimeoutException: Waiting for leader address of WebMonitorEndpoint timed out after 30000 ms.
        at org.apache.flink.util.concurrent.FutureUtils$Timeout.run(FutureUtils.java:1113)
        at org.apache.flink.util.concurrent.Executors$DirectExecutor.execute(Executors.java:60)
        at org.apache.flink.util.concurrent.FutureUtils.lambda$orTimeout$12(FutureUtils.java:457)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
