### ISSUE TITLE
[Bug] Trigger Savepoint Custom Savepoint function was unavailable, raise a excetion.

### ISSUE THREAD

**Issue by himper** [apache/streampark#3964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jDK1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.15.4

### deploy mode

kubernetes-session

### What happened

Trigger Savepoint Custom Savepoint function was unavailable, raise a excetion.

### Error Exception

```log
java.util.concurrent.CompletionException: java.lang.reflect.InvocationTargetException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.streampark.flink.client.FlinkClient$.$anonfun$proxy$1(FlinkClient.scala:87)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.$anonfun$proxy$1(FlinkShimsProxy.scala:60)
	at org.apache.streampark.common.util.ClassLoaderUtils$.runAsClassLoader(ClassLoaderUtils.scala:38)
	at org.apache.streampark.flink.proxy.FlinkShimsProxy$.proxy(FlinkShimsProxy.scala:60)
	at org.apache.streampark.flink.client.FlinkClient$.proxy(FlinkClient.scala:82)
	at org.apache.streampark.flink.client.FlinkClient$.triggerSavepoint(FlinkClient.scala:72)
	at org.apache.streampark.flink.client.FlinkClient.triggerSavepoint(FlinkClient.scala)
	at org.apache.streampark.console.core.service.impl.SavePointServiceImpl.lambda$trigger$0(SavePointServiceImpl.java:325)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
Caused by: java.lang.RuntimeException: org.apache.flink.client.deployment.ClusterRetrieveException: Could not get the rest endpoint of flink-session-eks-1-15-4-998
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.lambda$createClusterClientProvider$1(KubernetesClusterDescriptor.java:105)
	at org.apache.flink.kubernetes.KubernetesClusterDescriptor.retrieve(KubernetesClusterDescriptor.java:148)
	at org.apache.streampark.flink.client.trait.KubernetesNativeClientTrait.executeClientAction(KubernetesNativeClientTrait.scala:117)
	at org.apache.streampark.flink.client.trait.KubernetesNativeClientTrait.executeClientAction$(KubernetesNativeClientTrait.scala:98)
	at org.apache.streampark.flink.client.impl.KubernetesNativeSessionClient$.executeClientAction(KubernetesNativeSessionClient.scala:46)
	at org.apache.streampark.flink.client.trait.KubernetesNativeClientTrait.doTriggerSavepoint(KubernetesNativeClientTrait.scala:137)
	at org.apache.streampark.flink.client.trait.KubernetesNativeClientTrait.doTriggerSavepoint$(KubernetesNativeClientTrait.scala:131)
	at org.apache.streampark.flink.client.impl.KubernetesNativeSessionClient$.doTriggerSavepoint(KubernetesNativeSessionClient.scala:234)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.triggerSavepoint(FlinkClientTrait.scala:167)
	at org.apache.streampark.flink.client.trait.FlinkClientTrait.triggerSavepoint$(FlinkClientTrait.scala:153)
	at org.apache.streampark.flink.client.impl.KubernetesNativeSessionClient$.triggerSavepoint(KubernetesNativeSessionClient.scala:46)
	at org.apache.streampark.flink.client.FlinkClientHandler$.triggerSavepoint(FlinkClientHandler.scala:56)
	at org.apache.streampark.flink.client.FlinkClientHandler.triggerSavepoint(FlinkClientHandler.scala)
	... 16 more
Caused by: org.apache.flink.client.deployment.ClusterRetrieveException: Could not get the rest endpoint of flink-session-eks-1-15-4-998
	... 29 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. We are closing this issue because it is outdated.
