### ISSUE TITLE
[Bug] Proxy and Session Issues with YARN HTTP Kerberos Authentication

### ISSUE THREAD

**Issue by Tidra** [apache/streampark#3978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.4
2.1.5

### Flink Version

1.16.2

### deploy mode

yarn-session

### What happened

After enabling Kerberos authentication for YARN HTTP, the following issues occur:
1. Cluster YARN sessions cannot be stopped: Attempts to stop YARN sessions result in an error stating that Kerberos authentication information cannot be obtained.
2. "Cluster Id" and "Flink Web UI" links on the job details page: These links fail to properly proxy YARN pages that require Kerberos authentication.
3. Displayed links in cluster YARN sessions: The links shown in the YARN session interface do not match the configured yarn-url.

当开启yarn-http的Kerberos认证后，存在以下问题：
1. 集群 yarn session 无法停止，直接报错无法获取Kerberos认证信息
4. 作业详情页中的 ”Cluster Id“ 链接和 ”Flink Web UI“ 链接 无法正确代理有Kerberos认证的yarn页面
5. 集群 yarn session 显示的链接并不是配置了yarn-url 的链接

### Error Exception

```log
2024-08-20 14:40:38 | WARN  | streampark-cluster-executor-0 | org.apache.hadoop.ipc.Client:792] Exception encountered while connecting to the server 
org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
        at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:179)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:392)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:623)
        at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:414)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:843)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:839)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:839)
        at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
        at org.apache.hadoop.ipc.Client.call(Client.java:1502)
        at org.apache.hadoop.ipc.Client.call(Client.java:1455)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
        at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
        at com.sun.proxy.$Proxy221.getApplicationReport(Unknown Source)
        at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getApplicationReport(ApplicationClientProtocolPBClientImpl.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy222.getApplicationReport(Unknown Source)
        at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getApplicationReport(YarnClientImpl.java:542)
        at org.apache.streampark.flink.client.impl.YarnSessionClient$.shutdown(YarnSessionClient.scala:250)
        at org.apache.streampark.flink.client.FlinkClientEntrypoint$.shutdown(FlinkClientEntrypoint.scala:77)
        at org.apache.streampark.flink.client.FlinkClientEntrypoint.shutdown(FlinkClientEntrypoint.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. Could you please fix this bug? We are looking forward to seeing your PR.

**Comment by wolfboys** [comment]
fixed
