### ISSUE TITLE
[Bug] notebook can't submit job 

### ISSUE THREAD

**Issue by yutaoChina** [apache/streampark#592]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 1.2.1
* **JVM version** (`java -version`):1.8
* **OS version** (`uname -a` if on a Unix-like system):linux centos7 

### Bug Description
open notebook,选择sql编写sql提交报错
2022-01-10 23:39:00 | INFO  | notebook-submit-executor-2 | com.streamxhub.streamx.flink.repl.interpreter.FlinkInterpreter ] [StreamX] Using Scala: version 2.11.12
java.lang.NoClassDefFoundError: org/apache/flink/api/scala/FlinkILoop
        at com.streamxhub.streamx.flink.repl.interpreter.FlinkInterpreter.open(FlinkInterpreter.scala:45)
        at com.streamxhub.streamx.console.core.service.impl.NoteBookServiceImpl.lambda$submit$0(NoteBookServiceImpl.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.api.scala.FlinkILoop
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
Exception in thread "notebook-submit-executor-2" java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/flink/api/scala/FlinkILoop
        at com.streamxhub.streamx.console.core.service.impl.NoteBookServiceImpl.lambda$submit$0(NoteBookServiceImpl.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/api/scala/FlinkILoop
        at com.streamxhub.streamx.flink.repl.interpreter.FlinkInterpreter.open(FlinkInterpreter.scala:45)
        at com.streamxhub.streamx.console.core.service.impl.NoteBookServiceImpl.lambda$submit$0(NoteBookServiceImpl.java:70)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.api.scala.FlinkILoop
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

### How to Reproduce 
Steps to reproduce the behavior, for example:

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

**Comment by Joephper** [comment]
嘿，我也遇到跟你一样的问题，不知道你解决了没有？是不是需要引入其他jar包之类的。
