### ISSUE TITLE
Couldn't deploy Yarn Application Cluster

### ISSUE THREAD

**Issue by VSMDD** [apache/streampark#616]
error log:
![image](https://user-images.githubusercontent.com/31095506/149130629-af50916c-6338-4989-938e-7bb6baacf243.png)

**Comment by RaiToKU** [comment]
尝试一下使用v1.2.0 release

**Comment by honghaoli9898** [comment]
看了下详细信息，不知什么原因在拷贝jar到container时没有拷贝进去
![image](https://user-images.githubusercontent.com/43817517/149468060-422a445f-52f2-47f9-8789-e1bece8bec58.png)

**Comment by jiarara** [comment]
我也遇到这个问题，使用 flink 1.13.1  ，streamx-console-service-1.2.1 ，
运行演示项目 quickstart-flink-1.2.0 . 
报错如下： 
2022-01-14 18:54:35,946 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not start cluster entrypoint YarnApplicationClusterEntryPoint.
org.apache.flink.runtime.entrypoint.ClusterEntrypointException: Failed to initialize the cluster entrypoint YarnApplicationClusterEntryPoint.
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:191) ~[quickstart-flink-1.2.0.jar:?]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:529) [quickstart-flink-1.2.0.jar:?]
	at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.main(YarnApplicationClusterEntryPoint.java:111) [flink-dist_2.11-1.13.1.jar:1.13.1]
Caused by: java.lang.AbstractMethodError: org.apache.flink.runtime.entrypoint.ClusterEntrypoint.createSerializableExecutionGraphStore(Lorg/apache/flink/configuration/Configuration;Lorg/apache/flink/runtime/concurrent/ScheduledExecutor;)Lorg/apache/flink/runtime/dispatcher/ArchivedExecutionGraphStore;

![image](https://user-images.githubusercontent.com/5716373/149509652-2b4a7024-7477-47c9-b923-1ee1bcdf6429.png)
![image](https://user-images.githubusercontent.com/5716373/149509770-70370b8d-d591-4bf6-a503-eb0a295854cc.png)

**Comment by VSMDD** [comment]
这个问题我找到什么原因了，在yarn上看对应的applicationid 日志，因为用户没有streamx中存放在hdfs上的plugins和shims下jar的权限，求改权限即可
