### ISSUE TITLE
[Bug] startup fail becase  NullPointerException occurred

### ISSUE THREAD

**Issue by iture123** [apache/streampark#925]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

run bin/startup.sh failed

### StreamX Version

1.2.3

### Java Version

1.8.0_301

### Flink Version

no

### Scala Version of Flink

2.11.12

### Error Exception

```log
hadoop@hadoop-PC:/app/streamx-console-service-1.2.3$ bin/startup.sh 

           .+.                                                 
     _____/ /_________  ____ _____ ___  _  __                  
    / ___/ __/ ___/ _ \/ __ `/ __ `__ \| |/_/                  
   (__  ) /_/ /  /  __/ /_/ / / / / / />   <                   
  /____/\__/_/   \___/\__,_/_/ /_/ /_/_/|_|                    
                                        |/                     
                                        .                      
  • WebSite:  http://www.streamxhub.com
  • GitHub :  http://github.com/streamxhub/streamx
  • Gitee  :  http://gitee.com/streamxhub/streamx
           ────────  Make stream processing easier ô~ô!

[StreamX] Using APP_BASE:   /app/streamx-console-service-1.2.3
[StreamX] Using APP_HOME:   /app/streamx-console-service-1.2.3
[StreamX] Using JRE_HOME:   /ide/jdk/jdk1.8.0_301
[StreamX] Using APP_PID:   /app/streamx-console-service-1.2.3/.pid
[StreamX] Usage: properties file:application.yml 
[StreamX] Using HADOOP_HOME:   /app/hadoop-2.7.7
[StreamX] StreamX start successful. pid: 74570
hadoop@hadoop-PC:/app/streamx-console-service-1.2.3$ cat logs/error.2022-04-09.log 
2022-04-09 22:22:42.239 StreamX [main] ERROR o.s.boot.SpringApplication:837 - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at com.streamxhub.streamx.console.StreamXConsole.main(StreamXConsole.java:78)
Caused by: java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.storageInitialize(EnvInitializer.java:154)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.run(EnvInitializer.java:91)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
        ... 3 common frames omitted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinzhuxiansheng** [comment]
You can check whether it is because of directory permissions
