### ISSUE TITLE
[Bug] SettingServiceImpl.getMavenRepository throws NullPointerException

### ISSUE THREAD

**Issue by lxq970127** [apache/streampark#990]
### Search before asking

- [x] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

run streamx server start success,but web login,error occurred.
"Sorry, resource not found"

### StreamX Version

1.2.3

### Java Version

1.8

### Flink Version

1.14.4

### Scala Version of Flink

2.12

### Error Exception

```log
Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
        at com.streamxhub.streamx.console.StreamXConsole.main(StreamXConsole.java:77)
Caused by: java.lang.NullPointerException: null
        at com.streamxhub.streamx.console.core.service.impl.SettingServiceImpl.getMavenRepository(SettingServiceImpl.java:140)
        at com.streamxhub.streamx.console.core.service.impl.SettingServiceImpl$$FastClassBySpringCGLIB$$94ee097c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at com.streamxhub.streamx.console.core.service.impl.SettingServiceImpl$$EnhancerBySpringCGLIB$$a19ee665.getMavenRepository(<generated>)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.initInternalConfig(EnvInitializer.java:107)
        at com.streamxhub.streamx.console.core.runner.EnvInitializer.run(EnvInitializer.java:87)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
        ... 3 common frames omitted
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxq970127** [comment]
![image](https://user-images.githubusercontent.com/35163914/165432108-6b6f96ff-1fff-4a03-8ac3-cd4038bf7c27.png)

**Comment by lxq970127** [comment]
前端页面登录报405,因为前端访问服务器端口是1000,而服务器的真正端口是10000,我将前端端口手动改成10000后修复了这个问题,但是又报错没有权限,看了数据库里面应该是存在对应关系的.
![image](https://user-images.githubusercontent.com/35163914/165477780-1b36c413-2469-4915-a442-73016ee87d5b.png)
![image](https://user-images.githubusercontent.com/35163914/165478339-e87f067c-b816-483e-bd2b-cd6d919fdeae.png)
